#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) uniform sampler3D tempAndDensity_field_in;
layout(set = 1, binding = 2) uniform writeonly image3D tempAndDensity_field_out;

layout(push_constant) uniform Constants{
    vec2  location;
    float tempTarget;
    float ambientTemp;
    float radius;
    float tempRate;
    float densityRate;
    float decayRate;
    float dt;
    float time;
};


ivec2 gid = ivec2(gl_GlobalInvocationID);
ivec2 grid_size = textureSize(tempAndDensity_field_in, 0).xy;
vec2 uv = (vec2(gid) + 0.5)/grid_size.xy;
vec4 valuesOut = vec4(0);

float emitTemperature(float oldTemp){
    return max(oldTemp, (tempTarget - ambientTemp));
}

void main() {
    if(gid.x >= grid_size.x || gid.y >= grid_size.y) return;

    vec2 values = texture(tempAndDensity_field_in, vec3(fract(uv), 0.5)).xy;
    float temp = values.x;
    float newTemp = temp + (1 - exp(-tempRate * dt)) * (tempTarget - temp);

    float density = values.y;
    float newDensity = density + densityRate * dt;
    //    newDensity *= exp(-decayRate * time);

    vec2 d = (location - uv);
    valuesOut.x = newTemp * exp(-dot(d, d)/radius);
    valuesOut.y = newDensity  * exp(-dot(d, d)/radius);

    imageStore(tempAndDensity_field_out, ivec3(gid, 0), valuesOut);
}
