#version 460

#extension GL_EXT_debug_printf : enable
#include "models.glsl"

layout(local_size_x = 512) in;

void main() {
    const uint index = gl_GlobalInvocationID.x;
    if(index >= counters.slots_used) return;

    const vec3 position = draw[index].aabb.xyz;
    const float distance_to_cam =  computeDistanceToCamera(position);

    distance_to_camera[0].data[index] = floatBitsToUint(distance_to_cam);
    draw[index].aabb.w = distance_to_cam;
}