#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

#include "sim.glsl"

layout(set = 1, binding = 5, r32f) uniform writeonly image3D outImage;

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.xyz);
    if (outOfBounds(id)) {
        return;
    }

    if (obstacleAt(id) > 0.5) {
        imageStore(outImage, id, vec4(0.0));
        return;
    }

    float l = obstacleAt(id + ivec3(-1, 0, 0)) > 0.5 ? 0.0 : velocityAt(id + ivec3(-1, 0, 0)).x;
    float r = obstacleAt(id + ivec3( 1, 0, 0)) > 0.5 ? 0.0 : velocityAt(id + ivec3( 1, 0, 0)).x;
    float b = obstacleAt(id + ivec3( 0,-1, 0)) > 0.5 ? 0.0 : velocityAt(id + ivec3( 0,-1, 0)).y;
    float t = obstacleAt(id + ivec3( 0, 1, 0)) > 0.5 ? 0.0 : velocityAt(id + ivec3( 0, 1, 0)).y;
    float d = obstacleAt(id + ivec3( 0, 0,-1)) > 0.5 ? 0.0 : velocityAt(id + ivec3( 0, 0,-1)).z;
    float u = obstacleAt(id + ivec3( 0, 0, 1)) > 0.5 ? 0.0 : velocityAt(id + ivec3( 0, 0, 1)).z;

    float div = 0.5 * ((r - l) / sim.invGridSizeDt.x + (t - b) / sim.invGridSizeDt.y + (u - d) / sim.invGridSizeDt.z);
    imageStore(outImage, id, vec4(div));
}
