#version 460

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

#include "sim.glsl"

layout(set = 1, binding = 5, r32f) uniform writeonly image3D outImage;

float pressureAt(ivec3 id) {
    if (outOfBounds(id) || obstacleAt(id) > 0.5) {
        return 0.0;
    }
    return texture(pressureTex, uvwFromId(id)).r;
}

void main() {
    ivec3 id = ivec3(gl_GlobalInvocationID.xyz);
    if (outOfBounds(id)) {
        return;
    }

    if (obstacleAt(id) > 0.5) {
        imageStore(outImage, id, vec4(0.0));
        return;
    }

    float d = texture(divergenceTex, uvwFromId(id)).r;
    float p =
        pressureAt(id + ivec3(-1, 0, 0)) +
        pressureAt(id + ivec3( 1, 0, 0)) +
        pressureAt(id + ivec3( 0,-1, 0)) +
        pressureAt(id + ivec3( 0, 1, 0)) +
        pressureAt(id + ivec3( 0, 0,-1)) +
        pressureAt(id + ivec3( 0, 0, 1));

    imageStore(outImage, id, vec4((p - d) / 6.0));
}
