#version 460

#include "constants.glsl"

layout(local_size_x = WORKGROUP_RES, local_size_y = WORKGROUP_RES, local_size_z = 1) in;

void main() {
    uvec3 currentThread = gl_GlobalInvocationID;
    uvec2 coord = currentThread.xy;
    uint bandIdx = currentThread.z;

    vec3 displacementCenter = ShuffleDisplacement(imageLoad(DisplacementBuffer[bandIdx], ivec2(coord)).xyz);
    vec3 displacementRight = ShuffleDisplacement(imageLoad(DisplacementBuffer[bandIdx], ivec2((coord + uvec2(1u, 0u)) & (_SimulationRes - 1u))).xyz);
    vec3 displacementUp = ShuffleDisplacement(imageLoad(DisplacementBuffer[bandIdx], ivec2((coord + uvec2(0u, 1u)) & (_SimulationRes - 1u))).xyz);

    float pixelSize = _PatchSize[bandIdx] / float(_SimulationRes);

    displacementCenter.xz *= _Choppiness * 0.7;
    displacementRight.xz *= _Choppiness * 0.7;
    displacementUp.xz *= _Choppiness * 0.7;

    displacementCenter.y *= _Amplification;
    displacementRight.y *= _Amplification;
    displacementUp.y *= _Amplification;

    vec3 p0;
    vec3 p1;
    vec3 p2;
    EvaluateDisplacedPoints(displacementCenter, displacementRight, displacementUp, pixelSize, p0, p1, p2);

    imageStore(SurfaceGradientBuffer[bandIdx], ivec2(coord), vec4(evaluate_surface_gradients(p0, p1, p2), 1.0));
}
