#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable

struct Bounds {
    vec3 min;
    vec3 max;
};

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) uniform sampler3D force_field_in;
layout(set = 1, binding = 2) uniform writeonly image3D force_field_out;
layout(set = 2, binding = 0) uniform sampler3D tempAndDensityField;

layout(set = 3, binding = 0, scalar) buffer Cosntants {
    mat4 worldToVoxel;
    mat4 voxelToWorld;
    Bounds domain;
    Bounds emitterBounds;
    ivec3 resolution;
    vec3 up;
    float ambientTemp;
    float minValue;
    float maxValue;
    float tempFactor;
    float densityFactory;
    uint numCells;
};

#include "smoke_common.glsl"

void main() {
    ivec3 gid = ivec3(gl_GlobalInvocationID);
    if(any(greaterThanEqual(gid, resolution))) return;

    vec2 values = texelFetch(tempAndDensityField, gid, 0).xy;
    float temp = values.x;
    float density = values.y;
    vec3 buoyancy =  (densityFactory * density + tempFactor * (temp - ambientTemp)) * up;
    imageStore(force_field_out, gid, vec4(buoyancy, 0));

}