#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_debug_printf : enable

struct Bounds {
    vec3 min;
    vec3 max;
};

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 0, binding = 0) uniform sampler3D tempAndDensityField;
layout(set = 1, binding = 2) uniform writeonly image3D tempAndDensityFieldOut;

layout(set = 2, binding = 0, scalar) buffer Cosntants {
    mat4 worldToVoxel;
    mat4 voxelToWorld;
    Bounds domain;
    Bounds emitterBounds;
    ivec3 resolution;
    vec3 up;
    float ambientTemp;
	float tempSum;
    float minValue;
    float maxValue;
    float tempFactor;
    float densityFactory;
    float smokeDecayFactor;
    float temperatureDecayFactor;
    uint numCells;
};

#include "smoke_common.glsl"

void main() {
    ivec3 gid = ivec3(gl_GlobalInvocationID);
    if(any(greaterThanEqual(gid, resolution))) return;

    vec2 values = texelFetch(tempAndDensityField, gid, 0).xy * (1 - vec2(temperatureDecayFactor, smokeDecayFactor));
    float temp = values.x;
    float density = values.y;

    imageStore(tempAndDensityFieldOut, gid, vec4(temp, density, 0, 0));

}
