#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_debug_printf : enable

struct Bounds {
    vec3 min;
    vec3 max;
};

layout(local_size_x = 1) in;

layout(set = 0, binding = 0, scalar) buffer Constants {
    mat4 worldToVoxel;
    mat4 voxelToWorld;
    Bounds domain;
    Bounds emitterBounds;
    ivec3 resolution;
    vec3 up;
    float ambientTemp;
    float tempSum;
    float minValue;
    float maxValue;
    float tempFactor;
    float densityFactory;
    float smokeDecayFactor;
    float temperatureDecayFactor;
    uint numCells;
};

void main() {
    ambientTemp = numCells == 0u ? 0.0 : tempSum / float(numCells);
//    debugPrintfEXT("sum: %f, ambient temp: %f\n", tempSum, ambientTemp);
}
