#version 460

#include "shared.glsl"
#include "hash.glsl"

layout(local_size_x = 256) in;

layout(set = 1, binding = 0) buffer ParticlePosition {
    vec4 position[];
};

layout(set = 1, binding = 4) buffer HashMap {
    int hashes[];
};

int i = int(gl_GlobalInvocationID.x);

void main() {
    if(i >= numParticles) return;

    vec2 pos = position[i].xy;
    hashes[i] = computeHash(pos);
    position[i].z = computeHash(pos);
}