#version 460

#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 1024) in;

layout(set = 0, binding = 2) buffer ActivationUffer {
    float values[];
} activation[];

layout(set = 1, binding = 1, std430) readonly buffer TestLabels {
    int testLabels[];
};

layout(set = 1, binding = 3) buffer TestResults {
    int results[];
};

layout(push_constant) uniform Constants {
    uint layers[8];
    uint epoch;
    uint layerIndex;
    uint batch;
    uint batchSize;
    uint numLayers;
    float eta;
};

float a[10] = float[10](0, 0, 0, 0, 0, 0, 0, 0, 0 , 0);


int argmax() {
    uint outputLayer = numLayers - 1;
    uint numActivations = layers[outputLayer];
    uint start = gl_GlobalInvocationID.x * numActivations;

//    debugPrintfEXT("gid: %u, start: %u, size: %u, L: %u\n", gl_GlobalInvocationID.x, start, numActivations, outputLayer);

    float maxVal = 1e-20;
    int maxIndex = -1;
    for(int i = 0; i < numActivations; ++i) {
        uint j = start + i;
        float al = activation[outputLayer].values[j];
        a[i] = al;
        if(maxVal < al) {
            maxVal = al;
            maxIndex = i;
        }
    }
    return maxIndex;
}

void main() {
    if (gl_GlobalInvocationID.x >= batchSize) {
        return;
    }

    int label = testLabels[gl_GlobalInvocationID.x];
    results[gl_GlobalInvocationID.x] = int(argmax() == label);

//    debugPrintfEXT("y: %d, x: %d, a: [%f, %f, %f, %f, %f, %f, %f, %f, %f, %f] \n"
//    , label, argmax(), a[0], a[1], a[2], a[3], a[4], a[5], a[6], a[7], a[8], a[9]);
}
