#version 460

layout(local_size_x = 1, local_size_y = 1024) in;

#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 1, local_size_y = 1024) in;

layout(set = 0, binding = 0) buffer WeightsBUffer {
    float values[];
} weight[];

layout(set = 0, binding = 1) buffer BiasBuffer {
    float values[];
} bias[];

layout(set = 0, binding = 2) buffer ActivationBuffer {
    float values[];
} activation[];

layout(set = 0, binding = 3) buffer IntermediateWeightsBUffer {
    float values[];
} intermediate_weights[];

layout(set = 0, binding = 4) buffer Delta {
    float values[];
} delta[];

layout(set = 0, binding = 5) buffer NablaWeights {
    float values[];
} nablaWeights[];

layout(set = 0, binding = 6) buffer NablaBias {
    float values[];
} nablaBias[];


layout(push_constant) uniform Constants {
    uint layers[8];
    uint epoch;
    uint layer;
    uint batch;
    uint batchSize;
    uint numLayers;
    float eta;
};

shared float localSum[32];

float cost_derivative(float a, float y) {
    return a - y;
}

float sigmoid(float z) {
    return 1.0/(1.0 + exp(-z));
}

float sigmoid_prime(float z) {
    float sig = sigmoid(z);
    return (1 - sig) * sig;
}

void main() {
    const uint l = layers[layer];
    const uint l1 = layers[layer + 1];
    const uint l0 = layers[layer - 1];
    const uint j = gl_WorkGroupID.x;
    const uint k = gl_LocalInvocationID.y;

    if (j >= l) {
        return;
    }

    const uint row = k * l;
    const float w = k < l1 ? weight[layer].values[row + j] : 0.0;
    const float d1 = k < l1 ? delta[layer + 1].values[k] : 0.0;
    float sum = subgroupAdd(w * d1);

    if (subgroupElect()) {
        localSum[gl_SubgroupID] = sum;
    }

    barrier();

    if (subgroupAll(gl_SubgroupID < 1)) {
        float s = localSum[gl_SubgroupInvocationID];
        s = subgroupAdd(s);

        if (subgroupElect()) {
            const float z = intermediate_weights[layer - 1].values[j];
            const float d = s * sigmoid_prime(z);
            const uint prevRow = j * l0;

            delta[layer].values[j] = d;
            nablaBias[layer - 1].values[j] = d;

            for (uint i = 0; i < l0; ++i) {
                nablaWeights[layer - 1].values[prevRow + i] = d * activation[layer - 1].values[i];
            }
        }
    }
}
