#version 460

#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_vote : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 1024, local_size_y = 1) in;

layout(set = 0, binding = 0) buffer WeightsBUffer {
    float values[];
} weight[];

layout(set = 0, binding = 1) buffer BiasBUffer {
    float values[];
} bias[];

layout(set = 0, binding = 2) buffer ActivationUffer {
    float values[];
} activation[];

layout(set = 0, binding = 3) buffer IntermediateWeightsBUffer {
    float values[];
} intermediate_weights[];

layout(set = 0, binding = 4) buffer Delta {
    float values[];
} delta[];

layout(set = 0, binding = 5) buffer NablaWeights {
    float values[];
} nablaWeights[];

layout(set = 0, binding = 6) buffer NablaBias {
    float values[];
} nablaBias[];

layout(set = 1, binding = 0, std430) readonly buffer TrainingImages {
    float trainingImages[];
};

layout(set = 1, binding = 1, std430) readonly buffer TrainingLabels {
    int trainingLabels[];
};


layout(push_constant) uniform Constants {
    uint layers[8];
    uint epoch;
    uint layer;
    uint batch;
    uint batchSize;
    uint numLayers;
    float eta;
};

float cost_derivative(float a, float y) {
    return a - y;
}

float sigmoid(float z) {
    return 1.0/(1.0 + exp(-z));
}

float sigmoid_prime(float z) {
    float sig = sigmoid(z);
    return (1 - sig) * sig;
}

void main() {
    const uint l = layers[layer];
    const uint l1 = layers[layer + 1];
    const uint j = gl_WorkGroupID.x;
    const uint imageOffset = gl_WorkGroupID.y;
    const uint k = gl_LocalInvocationID.x;

    if (j >= l1) {
        return;
    }

    const uint sampleIndex = batch * batchSize + imageOffset;
    const uint outputIndex = imageOffset * l1 + j;
    const int y = trainingLabels[sampleIndex];
    const float a = activation[layer + 1].values[outputIndex];
    const float z = intermediate_weights[layer].values[outputIndex];
    const float d = cost_derivative(a, float(y == int(j))) * sigmoid_prime(z);

    if (k == 0) {
        delta[layer + 1].values[outputIndex] = d;
        nablaBias[layer].values[outputIndex] = d;
    }

    if (k < l) {
        const uint row = imageOffset * (l * l1) + j * l;
        const uint inputIndex = imageOffset * l + k;
        nablaWeights[layer].values[row + k] = d * activation[layer].values[inputIndex];
    }
}
