#version 460

layout(local_size_x = 256) in;

layout(set = 0, binding = 0) readonly buffer XBuffer {
    float x[];
};

layout(set = 0, binding = 1) writeonly buffer ResultBuffer {
    float result[];
};

layout(push_constant) uniform Constants {
    uvec2 shapeX;
    uvec2 shapeResult;
};

void main() {
    uint index = gl_GlobalInvocationID.x;
    uint size = shapeResult.x * shapeResult.y;
    if (index >= size) {
        return;
    }

    float s = 1.0 / (1.0 + exp(-x[index]));
    result[index] = (1.0 - s) * s;
}
