#version 460


#include "domain.glsl"
#define MIN_BOUNCES 3

layout(set = 1, binding = 0) uniform accelerationStructure topLevelAs;
layout(set = 2, binding = 11, rgba32f) uniform image2D global_images[];


const float Tmin = 0;
const float Tmax = FLT_MAX;

layout(location = 0) rayPayload HitRecord hRec;

void init(out HitRecord hRec, vec2 xi);

vec3 computeRadiance();

void main() {

    vec3 radiance = vec3(0);
    hRec.rngState = initRNG(vec2(gl_LaunchID), vec2(gl_LaunchSize), frame);

    if(adaptiveSampling == 0) {
        for (uint i = 0; i < maxSamples; ++i) {
            radiance += computeRadiance();
        }
        radiance /= maxSamples;
    }else {
        if(currentSample >= maxSamples) return;

        radiance = computeRadiance();
        vec3 dst = imageLoad(render_target, ivec2(gl_LaunchID.xy)).rgb;

        float t = 1/float(currentSample + 1);
        radiance = mix(dst, radiance, t);
    }

    imageStore(render_target, ivec2(gl_LaunchID.xy), vec4(radiance, 1));
}

void init(out HitRecord hRec, vec2 xi) {
    const vec2 pixelCenter = vec2(gl_LaunchID.xy) + xi;
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSize.xy);
    vec2 d = inUV * 2.0 - 1.0;

    vec4 target = inverse_projection * vec4(d.x, d.y, 1, 1) ;

    hRec.brdfWeigth = vec3(1);
    hRec.Le = vec3(0);
    hRec.Ld = vec3(0);
    hRec.wi = (inverse_view * vec4(normalize(target.xyz), 0)).xyz;
    hRec.x = (inverse_view * vec4(0,0,0,1)).xyz;
    hRec.hit = true;
    hRec.transmission = vec3(1);
    hRec.eta = 1;
}

vec3 computeRadiance() {

    init(hRec, vec2(rand(hRec.rngState), rand(hRec.rngState)));

    vec3 throughput = vec3(1);
    vec3 radiance = vec3(0);
    uint flags = gl_RayFlagsNoOpaque;

    for(uint b = 0; b < maxBounce; ++b) {
        traceRay(topLevelAs, flags, 0xFF, 0, 0, 0, hRec.x, Tmin, hRec.wi, Tmax, 0);
        if(!hRec.hit) {
            radiance += throughput * hRec.brdfWeigth;
            break;
        }

        throughput *= hRec.transmission;
        radiance += throughput * hRec.Le;
        radiance += throughput * hRec.Ld;

        if(b > MIN_BOUNCES && b < (maxBounce - 1)){
            float rrProbability = min(0.95, luminance(throughput));
            if(rrProbability < rand(hRec.rngState)){
                break;
            }
            throughput /= rrProbability;
        }

        throughput *= hRec.brdfWeigth;
        hRec.transmission = vec3(1);
    }
    return radiance;
}