#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_shader_atomic_float : enable
#extension GL_EXT_debug_printf : enable

#define CONSTRAINT_SOLVE_TYPE_GRAPH_COLOR 0
#define CONSTRAINT_SOLVE_TYPE_JACOBI 1

layout(local_size_x = 1024) in;

#include "../shared.glsl"

layout(set = 0, binding = 0) buffer POINT_MASSES_IN {
    vec4 positions[];
};

layout(set = 1, binding = 0, scalar) buffer CONSTRAINT_IDS {
    int constraintIDs[];
};

layout(set = 1, binding = 1, scalar) buffer REST_LENGTHS {
    float restLengths[];
};

layout(set = 1, binding = 3, scalar) buffer CORRECTIONS {
    vec3 corrections[];
};

layout(set = 1, binding = 4, scalar) buffer INV_MASS {
    float invMass[];
};

void main() {
    if (gl_GlobalInvocationID.x >= numConstraints) return;

    uint cNr = int(gl_GlobalInvocationID.x) + constraintOffset;

    int id0 = constraintIDs[2 * cNr];
    int id1 = constraintIDs[2 * cNr + 1];

    float w0 = invMass[id0];
    float w1 = invMass[id1];
    float w = w0 + w1;

    if (w == 0.0) return;

    vec3 p0 = positions[id0].xyz;
    vec3 p1 = positions[id1].xyz;
    vec3 d = p1 - p0;
    float l = length(d);
    vec3 n = l == 0 ? vec3(0) : d/l;

    float l0 = restLengths[cNr];
    vec3 dP = n * (l - l0) / w;

    if(solveType == CONSTRAINT_SOLVE_TYPE_JACOBI) {
        vec3 curr = w0 * dP;
        atomicAdd(corrections[id0].x, curr.x);
        atomicAdd(corrections[id0].y, curr.y);
        atomicAdd(corrections[id0].z, curr.z);

        curr = -w1 * dP;
        atomicAdd(corrections[id1].x, curr.x);
        atomicAdd(corrections[id1].y, curr.y);
        atomicAdd(corrections[id1].z, curr.z);
    } else {
        vec3 curr = w0 * dP;
        atomicAdd(positions[id0].x, curr.x);
        atomicAdd(positions[id0].y, curr.y);
        atomicAdd(positions[id0].z, curr.z);

        curr = -w1 * dP;
        atomicAdd(positions[id1].x, curr.x);
        atomicAdd(positions[id1].y, curr.y);
        atomicAdd(positions[id1].z, curr.z);
    }
}