#version 450

#extension GL_EXT_nonuniform_qualifier : enable

#include "noise.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(set = 0, binding = 11) writeonly uniform image3D global_images[];

#define lowFreqencyNoises global_images[nonuniformEXT(lowFrequencyNoisesIndex)]
#define highFreqencyNoises global_images[nonuniformEXT(highFrequencyNoisesIndex)]

layout(push_constant) uniform Constants {
    uint lfSize;
    uint hfSize;
    uint lowFrequencyNoisesIndex;
    uint highFrequencyNoisesIndex;
};


void main(){
    ivec3 gid = ivec3(gl_GlobalInvocationID);
    vec3 uv = vec3(gid)/float(lfSize);

    vec4 col = vec4(0.);

    float freq = 4.;

    float pfbm= mix(1., perlinfbm(uv, 4., 7), .5);
    pfbm = abs(pfbm * 2. - 1.); // billowy perlin noise

    col.g += worleyFbm(uv, freq);
    col.b += worleyFbm(uv, freq*2.);
    col.a += worleyFbm(uv, freq*4.);
    col.r += remap(pfbm, 0., 1., col.g, 1.); // perlin-worley

    imageStore(lowFreqencyNoises, ivec3(gl_GlobalInvocationID), col);


    uv = vec3(gid)/float(hfSize);
    freq = 8.;

    col = vec4(0);
    col.r += worleyFbm(uv, freq);
    col.g += worleyFbm(uv, freq*2.);
    col.b += worleyFbm(uv, freq*4.);

    imageStore(highFreqencyNoises, gid, col);
}