#version 460

#include "atm_uniforms.glsl"

#define PLANET_RADIUS_OFFSET 0.01

layout(local_size_x = 1, local_size_y = 1, local_size_z = 64) in;

layout(set = 1, binding = 10) uniform sampler2D global_textures[];
layout(set = 1, binding = 10) uniform sampler2D global_textures_3d[];
layout(set = 1, binding = 11) uniform writeonly image2D global_images[];

#include "common_functions.glsl"

vec3 ComputeOpticalLengthAt(vec3 position) {
    return exp(-(
    ATMOSPHERE.rayleigh_scattering * ComputeOpticalLengthAt(ATMOSPHERE, ATMOSPHERE.rayleigh_density, position) +
    ATMOSPHERE.mie_extinction * ComputeOpticalLengthAt(ATMOSPHERE, ATMOSPHERE.mie_density, position) +
    ATMOSPHERE.ozone_extinction * ComputeOpticalLengthAt(ATMOSPHERE, ATMOSPHERE.ozone_density, position)));
}

vec3 ComputeStatteringAt(vec3 position) {
    return exp(-(
        ATMOSPHERE.rayleigh_scattering * ComputeOpticalLengthAt(ATMOSPHERE, ATMOSPHERE.rayleigh_density, position) +
        ATMOSPHERE.mie_scattering * ComputeOpticalLengthAt(ATMOSPHERE, ATMOSPHERE.mie_density, position)));
}

const float SPHERE_SAMPLES = 64.0;
const float GOLDEN_RATIO = 1.6180339;

vec3 ComputeScatteredLuminance(vec3 worldPosition, vec3 worldDirection, vec3 sunDirection, float sampleCount
                                                                                    , out vec3 multiscattering) {

    multiscattering = vec3(0);

    float t = DistanceToAtmosphere(ATMOSPHERE, worldPosition, worldDirection);
    if(t == -1.0) return vec3(0);

    vec3 accumTrans = vec3(1.0, 1.0, 1.0);
    vec3 accumLight = vec3(0.0, 0.0, 0.0);
    float oldRayShift = 0;

    float dt = t / float(sampleCount);

    vec3 luminance = vec3(0);
    for (int i = 0; i < sampleCount; i++)
    {
        /* Sampling at 1/3rd of the integration step gives better results for exponential
           functions */
        float newRayShift = t * (float(i) + 0.3) / sampleCount;
        dt = newRayShift - oldRayShift;
        vec3 newPos = worldPosition + newRayShift * worldDirection;
        oldRayShift = newRayShift;

        /* Raymarch shifts the angle to the sun a bit recalculate */
        vec3 upVector = normalize(newPos);
        float r = length(newPos);
        float mu = dot(sunDirection, upVector);
        vec3 transmittanceToSun = GetTransmittanceToTopAtmosphereBoundary(ATMOSPHERE, r, mu);
        vec3 mediumScattering = ComputeStatteringAt(newPos);
        vec3 mediumExtinction = ComputeOpticalLengthAt(newPos);

        /* TODO: This probably should be a texture lookup*/
        vec3 transIncreseOverInegrationStep = exp(-(mediumExtinction * dt));
        /* Check if current position is in earth's shadow */
        float earthIntersectionDistance = RaySphereIntersectNearest(newPos, sunDirection, vec3(0) + PLANET_RADIUS_OFFSET * upVector, ATMOSPHERE.bottom_radius);
        float inEarthShadow = earthIntersectionDistance == -1.0 ? 1.0 : 0.0;

        /* Light arriving from the sun to this point */
        vec3 sunLight = inEarthShadow * transmittanceToSun * mediumScattering * IsotropicPhaseFunction();
        vec3 multiscatteredContInt =
        (mediumScattering - mediumScattering * transIncreseOverInegrationStep) / mediumExtinction;
        vec3 inscatteredContInt =
        (sunLight - sunLight * transIncreseOverInegrationStep) / mediumExtinction;
        /* For some reson I need to do this to avoid nans in multiscatteredLightInt ->
           precision error? */
        if (all(equal(transIncreseOverInegrationStep, vec3(1.0)))) {
            multiscatteredContInt = vec3(0.0);
            inscatteredContInt = vec3(0.0);
        }
        multiscattering += accumTrans * multiscatteredContInt;
        accumLight += accumTrans * inscatteredContInt;
        // accumLight = accumTrans;
        accumTrans *= transIncreseOverInegrationStep;
    }
    luminance = accumLight;
    return luminance;
}

shared vec3 MultiscattSharedMem[64];
shared vec3 LSharedMem[64];

void main() {
    const float sampleCount = 20;

    ivec2 gid = ivec2(gl_GlobalInvocationID);
    vec2 uv = GetUnitRangeFromTextureCoord((vec2(gid) + 0.5), MULTI_SCATTERING_TEXTURE_SIZE);


    float sunCosZenithAngle = uv.x * 2.0 - 1.0;
    vec3 sunDirection = vec3(0.0,sqrt(clamp(1.0 - sunCosZenithAngle * sunCosZenithAngle, 0.0, 1.0)), sunCosZenithAngle);
    float viewHeight = ATMOSPHERE.bottom_radius + clamp(uv.y + PLANET_RADIUS_OFFSET, 0.0, 1.0) *
                        (ATMOSPHERE.top_radius - ATMOSPHERE.bottom_radius - PLANET_RADIUS_OFFSET);

    vec3 worldPosition = vec3(0.0, 0.0, viewHeight);

    float sampleIdx = gl_LocalInvocationID.z;
    // local thread dependent raymarch
    {
        #define USE_HILL_SAMPLING 0
        #if USE_HILL_SAMPLING
        #define SQRTSAMPLECOUNT 8
        const float sqrtSample = float(SQRTSAMPLECOUNT);
        float i = 0.5 + float(sampleIdx / SQRTSAMPLECOUNT);
        float j = 0.5 + mod(sampleIdx, SQRTSAMPLECOUNT);
        float randA = i / sqrtSample;
        float randB = j / sqrtSample;

        float theta = 2.0 * PI * randA;
        float phi = PI * randB;
        #else
        /* Fibbonaci lattice -> http://extremelearning.com.au/how-to-evenly-distribute-points-on-a-sphere-more-effectively-than-the-canonical-fibonacci-lattice/ */
        float theta = acos(1.0 - 2.0 * (sampleIdx + 0.5) / SPHERE_SAMPLES);
        float phi = (2 * PI * sampleIdx) / GOLDEN_RATIO;
        #endif


        vec3 worldDirection = vec3(cos(theta) * sin(phi), sin(theta) * sin(phi), cos(phi));

        vec3 multiscattering;
        vec3 luminance = ComputeScatteredLuminance(worldPosition, worldDirection,sunDirection, sampleCount, multiscattering);

        MultiscattSharedMem[gl_LocalInvocationID.z] = multiscattering / SPHERE_SAMPLES;
        LSharedMem[gl_LocalInvocationID.z] = luminance / SPHERE_SAMPLES;
    }

    barrier();

    if (gl_LocalInvocationID.z < 32){
        MultiscattSharedMem[gl_LocalInvocationID.z] += MultiscattSharedMem[gl_LocalInvocationID.z + 32];
        LSharedMem[gl_LocalInvocationID.z] += LSharedMem[gl_LocalInvocationID.z + 32];
    }
    
    barrier();
    if (gl_LocalInvocationID.z < 16){
        MultiscattSharedMem[gl_LocalInvocationID.z] += MultiscattSharedMem[gl_LocalInvocationID.z + 16];
        LSharedMem[gl_LocalInvocationID.z] += LSharedMem[gl_LocalInvocationID.z + 16];
    }
    
    barrier();
    if (gl_LocalInvocationID.z < 8){
        MultiscattSharedMem[gl_LocalInvocationID.z] += MultiscattSharedMem[gl_LocalInvocationID.z + 8];
        LSharedMem[gl_LocalInvocationID.z] += LSharedMem[gl_LocalInvocationID.z + 8];
    }
    
    barrier();
    if (gl_LocalInvocationID.z < 4){
        MultiscattSharedMem[gl_LocalInvocationID.z] += MultiscattSharedMem[gl_LocalInvocationID.z + 4];
        LSharedMem[gl_LocalInvocationID.z] += LSharedMem[gl_LocalInvocationID.z + 4];
    }
    
    barrier();
    if (gl_LocalInvocationID.z < 2){
        MultiscattSharedMem[gl_LocalInvocationID.z] += MultiscattSharedMem[gl_LocalInvocationID.z + 2];
        LSharedMem[gl_LocalInvocationID.z] += LSharedMem[gl_LocalInvocationID.z + 2];
    }
    
    barrier();
    if (gl_LocalInvocationID.z < 1){
        MultiscattSharedMem[gl_LocalInvocationID.z] += MultiscattSharedMem[gl_LocalInvocationID.z + 1];
        LSharedMem[gl_LocalInvocationID.z] += LSharedMem[gl_LocalInvocationID.z + 1];
    }
    
    barrier();
    if (gl_LocalInvocationID.z != 0)
    return;

    vec3 MultiscattSum = MultiscattSharedMem[0];
    vec3 InScattLumSum = LSharedMem[0];

    const vec3 r = MultiscattSum;
    const vec3 SumOfAllMultiScatteringEventsContribution = vec3(1.0/ (1.0 -r.x), 1.0/ (1.0 -r.y), 1.0/ (1.0 -r.z));
    vec3 Lum = InScattLumSum * SumOfAllMultiScatteringEventsContribution;

    imageStore(multiScatteringImage, gid, vec4(Lum, 1.0));
}