#version 460
#extension GL_GOOGLE_include_directive : require

layout (local_size_x = 1, local_size_y = 1, local_size_z = 64) in;

layout(set = 1, binding = 10) uniform sampler2D global_textures[];
layout(set = 1, binding = 10) uniform sampler2D global_textures_3d[];
layout(set = 1, binding = 11) uniform writeonly image2D global_images[];

#include "common.glsl"

shared vec3 MultiScatAs1SharedMem[64];
shared vec3 LSharedMem[64];

float MultipleScatteringFactor = 1.0;

void main() {
    float MultiScatteringLUTRes = MULTI_SCATTERING_TEXTURE_SIZE.x;
    vec2 pixPos = vec2(gl_GlobalInvocationID.xy) + 0.5f;
    vec2 uv = pixPos / MultiScatteringLUTRes;


    uv = vec2(fromSubUvsToUnit(uv.x, MultiScatteringLUTRes), fromSubUvsToUnit(uv.y, MultiScatteringLUTRes));

    AtmosphereParameters Atmosphere = GetAtmosphereParameters();

    float cosSunZenithAngle = uv.x * 2.0 - 1.0;
    vec3 sunDir = vec3(0.0, sqrt(saturate(1.0 - cosSunZenithAngle * cosSunZenithAngle)), cosSunZenithAngle);
    // We adjust again viewHeight according to PLANET_RADIUS_OFFSET to be in a valid range.
    float viewHeight = Atmosphere.bottom_radius + saturate(uv.y + PLANET_RADIUS_OFFSET) * (Atmosphere.top_radius - Atmosphere.bottom_radius - PLANET_RADIUS_OFFSET);

    vec3 WorldPos = vec3(0.0f, 0.0f, viewHeight);
    vec3 WorldDir = vec3(0.0f, 0.0f, 1.0f);


    const bool ground = true;
    const float SampleCountIni = 20;// a minimum set of step is required for accuracy unfortunately
    const float DepthBufferValue = -1.0;
    const bool VariableSampleCount = false;
    const bool MieRayPhase = false;

    const float SphereSolidAngle = 4.0 * PI;
    const float IsotropicPhase = 1.0 / SphereSolidAngle;


    // Reference. Since there are many sample, it requires MULTI_SCATTERING_POWER_SERIE to be true for accuracy and to avoid divergences (see declaration for explanations)
    #define SQRTSAMPLECOUNT 8
    const float sqrtSample = float(SQRTSAMPLECOUNT);
    float i = 0.5f + float(gl_GlobalInvocationID.z / SQRTSAMPLECOUNT);
    float j = 0.5f + float(gl_GlobalInvocationID.z - float((gl_GlobalInvocationID.z / SQRTSAMPLECOUNT)*SQRTSAMPLECOUNT));
    {
        float randA = i / sqrtSample;
        float randB = j / sqrtSample;
        float theta = 2.0f * PI * randA;
        float phi = acos(1.0f - 2.0f * randB);	// uniform distribution https://mathworld.wolfram.com/SpherePointPicking.html
        //phi = PI * randB;						// bad non uniform
        float cosPhi = cos(phi);
        float sinPhi = sin(phi);
        float cosTheta = cos(theta);
        float sinTheta = sin(theta);
        WorldDir.x = cosTheta * sinPhi;
        WorldDir.y = sinTheta * sinPhi;
        WorldDir.z = cosPhi;
        SingleScatteringResult result = IntegrateScatteredLuminance(pixPos, WorldPos, WorldDir, sunDir, Atmosphere, ground, SampleCountIni, DepthBufferValue, VariableSampleCount, MieRayPhase, T_MAX_MAX, ivec2(0));

        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] = result.MultiScatAs1 * SphereSolidAngle / (sqrtSample * sqrtSample);
        LSharedMem[gl_GlobalInvocationID.z] = result.L * SphereSolidAngle / (sqrtSample * sqrtSample);
    }
    #undef SQRTSAMPLECOUNT

    SYNC_THREADS;

    // 64 to 32
    if (gl_GlobalInvocationID.z < 32)
    {
        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] += MultiScatAs1SharedMem[gl_GlobalInvocationID.z + 32];
        LSharedMem[gl_GlobalInvocationID.z] += LSharedMem[gl_GlobalInvocationID.z + 32];
    }
    SYNC_THREADS;

    // 32 to 16
    if (gl_GlobalInvocationID.z < 16)
    {
        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] += MultiScatAs1SharedMem[gl_GlobalInvocationID.z + 16];
        LSharedMem[gl_GlobalInvocationID.z] += LSharedMem[gl_GlobalInvocationID.z + 16];
    }
    SYNC_THREADS;

    // 16 to 8 (16 is thread group min hardware size with intel, no sync required from there)
    if (gl_GlobalInvocationID.z < 8)
    {
        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] += MultiScatAs1SharedMem[gl_GlobalInvocationID.z + 8];
        LSharedMem[gl_GlobalInvocationID.z] += LSharedMem[gl_GlobalInvocationID.z + 8];
    }
    SYNC_THREADS;
    if (gl_GlobalInvocationID.z < 4)
    {
        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] += MultiScatAs1SharedMem[gl_GlobalInvocationID.z + 4];
        LSharedMem[gl_GlobalInvocationID.z] += LSharedMem[gl_GlobalInvocationID.z + 4];
    }
    SYNC_THREADS;
    if (gl_GlobalInvocationID.z < 2)
    {
        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] += MultiScatAs1SharedMem[gl_GlobalInvocationID.z + 2];
        LSharedMem[gl_GlobalInvocationID.z] += LSharedMem[gl_GlobalInvocationID.z + 2];
    }
    SYNC_THREADS;
    if (gl_GlobalInvocationID.z < 1)
    {
        MultiScatAs1SharedMem[gl_GlobalInvocationID.z] += MultiScatAs1SharedMem[gl_GlobalInvocationID.z + 1];
        LSharedMem[gl_GlobalInvocationID.z] += LSharedMem[gl_GlobalInvocationID.z + 1];
    }
    SYNC_THREADS;
    if (gl_GlobalInvocationID.z > 0)
    return;

    vec3 MultiScatAs1			= MultiScatAs1SharedMem[0] * IsotropicPhase;	// Equation 7 f_ms
    vec3 InScatteredLuminance	= LSharedMem[0] * IsotropicPhase;				// Equation 5 L_2ndOrder

    // MultiScatAs1 represents the amount of luminance scattered as if the integral of scattered luminance over the sphere would be 1.
    //  - 1st order of scattering: one can ray-march a straight path as usual over the sphere. That is InScatteredLuminance.
    //  - 2nd order of scattering: the inscattered luminance is InScatteredLuminance at each of samples of fist order integration. Assuming a uniform phase function that is represented by MultiScatAs1,
    //  - 3nd order of scattering: the inscattered luminance is (InScatteredLuminance * MultiScatAs1 * MultiScatAs1)
    //  - etc.
    #if	MULTI_SCATTERING_POWER_SERIE==0
    vec3 MultiScatAs1SQR = MultiScatAs1 * MultiScatAs1;
    vec3 L = InScatteredLuminance * (1.0 + MultiScatAs1 + MultiScatAs1SQR + MultiScatAs1 * MultiScatAs1SQR + MultiScatAs1SQR * MultiScatAs1SQR);
    #else
    // For a serie, sum_{n=0}^{n=+inf} = 1 + r + r^2 + r^3 + ... + r^n = 1 / (1.0 - r), see https://en.wikipedia.org/wiki/Geometric_series
    const vec3 r = MultiScatAs1;
    const vec3 SumOfAllMultiScatteringEventsContribution = 1.0f / (1.0 - r);
    vec3 L = InScatteredLuminance * SumOfAllMultiScatteringEventsContribution;// Equation 10 Psi_ms
    #endif

    vec3 result = MultipleScatteringFactor * L;
    imageStore(multiScatteringImage, ivec2(gl_GlobalInvocationID), vec4(result, 1));
}