#ifndef ATMOSPHERE_SPECIALIZATION_GLSL
#define ATMOSPHERE_SPECIALIZATION_GLSL

#define TRANSMITTANCE_TEXTURE_SIZE ivec2(TRANSMITTANCE_TEXTURE_WIDTH, TRANSMITTANCE_TEXTURE_HEIGHT)
#define TRANSMITTANCE_TEXTURE_SIZE_F vec2(TRANSMITTANCE_TEXTURE_SIZE)

#define MULTI_SCATTERING_TEXTURE_SIZE ivec2(MULTI_SCATTERING_TEXTURE_WIDTH, MULTI_SCATTERING_TEXTURE_HEIGHT)
#define MULTI_SCATTERING_TEXTURE_SIZE_F vec2(MULTI_SCATTERING_TEXTURE_SIZE)

#define SKY_VIEW_TEXTURE_SIZE ivec2(SKY_VIEW_TEXTURE_WIDTH)
#define SKY_VIEW_TEXTURE_SIZE_F vec2(SKY_VIEW_TEXTURE_SIZE)

#define AREAL_PERSPECTIVE_TEXTURE_SIZE ivec3(AREAL_PERSPECTIVE_TEXTURE_WIDTH, AREAL_PERSPECTIVE_TEXTURE_HEIGHT, AREAL_PERSPECTIVE_TEXTURE_DEPTH)
#define AREAL_PERSPECTIVE_TEXTURE_SIZE_F vec3(AREAL_PERSPECTIVE_TEXTURE_SIZE)

layout(constant_id = 0) const int TRANSMITTANCE_TEXTURE_WIDTH = 256;
layout(constant_id = 1) const int TRANSMITTANCE_TEXTURE_HEIGHT = 64;

layout(constant_id = 2) const int MULTI_SCATTERING_TEXTURE_WIDTH = 32;
layout(constant_id = 3) const int MULTI_SCATTERING_TEXTURE_HEIGHT = 32;

layout(constant_id = 4) const int SKY_VIEW_TEXTURE_WIDTH = 192;
layout(constant_id = 5) const int SKY_VIEW_TEXTURE_HEIGHT = 128;

layout(constant_id = 6) const int AREAL_PERSPECTIVE_TEXTURE_WIDTH = 32;
layout(constant_id = 7) const int AREAL_PERSPECTIVE_TEXTURE_HEIGHT = 32;
layout(constant_id = 8) const int AREAL_PERSPECTIVE_TEXTURE_DEPTH = 32;

#endif // ATMOSPHERE_SPECIALIZATION_GLSL