#version 460

#include "atm_uniforms.glsl"

layout(local_size_x = 8, local_size_y = 4) in;

layout(set = 1, binding = 10) uniform sampler2D global_textures[];
layout(set = 1, binding = 10) uniform sampler3D global_textures_3d[];
layout(set = 1, binding = 11) uniform writeonly image2D global_images[];

#define transmittanceImage global_images[nonuniformEXT(atm.transmittanceImageIndex)]

#include "common.glsl"

vec3 IntegrateTransmission(AtmosphereParameters Atmosphere, vec3 WorldPos, vec3 WorldDir, float SampleCount) {
    float tMax = raySphereIntersectNearest(WorldPos, WorldDir, vec3(0), Atmosphere.top_radius);
    if(tMax == 0) return vec3(0);

    vec3 OpticalDepth = vec3(0.0);

    const float dt = tMax / SampleCount;
    for (int i = 0; i < SampleCount; ++i){
        float t = float(i) * dt;
        vec3 P = WorldPos + t * WorldDir;
        const MediumSampleRGB medium = sampleMediumRGB(P, Atmosphere);
        const vec3 SampleOpticalDepth = medium.extinction * dt;
        OpticalDepth += SampleOpticalDepth;
    }

    return OpticalDepth;
}

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID);
    vec2 pixPos = vec2(gid) + 0.5f;
    AtmosphereParameters Atmosphere = GetAtmosphereParameters();

    // Compute camera position from LUT coords
    vec2 uv = pixPos / TRANSMITTANCE_TEXTURE_SIZE_F;
    float viewHeight;
    float viewZenithCosAngle;
    UvToLutTransmittanceParams(Atmosphere, viewHeight, viewZenithCosAngle, uv);

    //  A few extra needed constants
    vec3 WorldPos = vec3(0.0f, 0.0f, viewHeight);
    vec3 WorldDir = vec3(0.0f, SafeSqrt(1.0 - viewZenithCosAngle * viewZenithCosAngle), viewZenithCosAngle);

    vec3 OpticalDepth = IntegrateTransmission(Atmosphere, WorldPos, WorldDir, 40);
    vec3 transmittance = exp(-OpticalDepth);

    imageStore(transmittanceImage, gid, vec4(transmittance, 0));
}

