#version 460

#define VIEW_PATCHES 0
#define VIEW_NORMALS 1
#define VIEW_JACOBIAN_NORMALS 2
#define VIEW_JACOBIAN 3
#define VIEW_JACOBIAN_EIGAN_VALUES 4
#define VIEW_JACOBIAN_EIGAN_VECTORS 5
#define VIEW_SURFACE_PROFILE 6

#define COMBINDED_PATCHES 1

#define SURFACE_PROFILE_BASIC 1
#define SURFACE_PROFILE_CHOPPY 2
#define SURFACE_PROFILE_JACOBIAN 4

#define BINDLESS_DESCRIPTOR_SET 1
#define OCEAN_UNIFORM_SET 2
#include "shading.glsl"

layout(local_size_x = 32, local_size_y = 32) in;

layout(set = 0, binding = 10) writeonly uniform image2D image;

layout(push_constant) uniform PushConstants {
    int view;
    int flag;
    float scale;
} pc;

float remap(float x, float a, float b, float c, float d) {
    float t = (x - a)/(b - a);
    return mix(c, d, t);
}

float fx(vec3 coord) {
    return texture(u_DmapSampler, coord).y;
}

float gx(vec3 coord) {
    Jacobian2D J = computeJacobian(coord.xy, int(coord.z));
    float lambda = u.choppiness;

    float Jxx = 1 + J.Dxx * lambda;
    float Jzz = 1 + J.Dzz * lambda;
    float Jzx = J.Dzx * lambda;
    float Jxz = J.Dxz * lambda;

    return Jxx * Jzz - Jxz * Jzx;
}


void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID);
    vec4 color = vec4(0, 0, 0, 1);

    if(pc.view < VIEW_SURFACE_PROFILE){
        vec2 uv = vec2(gid + 0.5)/vec2(gl_NumWorkGroups * gl_WorkGroupSize);
        vec2 gv = floor(uv * 2);
        uv = fract(uv * 2);

        float layer = gv.y * 2 + gv.x;
        vec3 loc = vec3(uv, layer);

        if(pc.view == VIEW_PATCHES) {
            vec3 disp = texture(u_DmapSampler, loc).xyz;

            disp.x *= u.choppiness;
            disp.z *= u.choppiness;

            color.xyz = disp;
        }else if (pc.view == VIEW_NORMALS) {
            vec2 slope = texture(u_NormalSampler, loc).xy;
            color.xyz = vec3(-slope.x, 1, -slope.y);
        }else if(pc.view == VIEW_JACOBIAN_NORMALS) {
            int layer = int(loc.z);
            vec2 p = loc.xy * u.horizontalLength[layer];

            Jacobian2D J = computeJacobian(p, layer);
            float lambda = u.choppiness;

            J.Dxx *= lambda;
            J.Dxz *= lambda;
            J.Dzx *= lambda;
            J.Dzz *= lambda;

            vec3 n = normalFromJacobian(p, layer, J);

            color.xyz = n;
        }else if(pc.view == VIEW_JACOBIAN) {
            int layer = int(loc.z);
            vec2 p = loc.xy * u.horizontalLength[layer];

            Jacobian2D J = computeJacobian(p, layer);
            float lambda = u.choppiness;

            float Jxx = 1 + J.Dxx * lambda;
            float Jzz = 1 + J.Dzz * lambda;
            float Jzx = J.Dzx * lambda;
            float Jxz = J.Dxz * lambda;

            float jD = Jxx * Jzz - Jxz * Jzx;
            color.xyz = 1 - jD.xxx;
        } else if(pc.view == VIEW_JACOBIAN_EIGAN_VALUES) {
            int layer = int(loc.z);
            vec2 p = loc.xy * u.horizontalLength[layer];

            Jacobian2D J = computeJacobian(p, layer);
            float lambda = u.choppiness;

            float Jxx = 1 + J.Dxx * lambda;
            float Jzz = 1 + J.Dzz * lambda;
            float Jzx = J.Dzx * lambda;
            float Jxz = J.Dxz * lambda;

            float left = 0.5 * (Jxx + Jzz);
            float right = 0.5 * pow(pow(Jxx - Jzz, 2) + 4 * Jxz * Jxz, 0.5);
            float J0 = left - right;
            float J1 = left + right;

            color.xy = vec2(J0, J1);
        } else if(pc.view == VIEW_JACOBIAN_EIGAN_VECTORS) {
            int layer = int(loc.z);
            vec2 p = loc.xy * u.horizontalLength[layer];

            Jacobian2D J = computeJacobian(p, layer);
            float lambda = u.choppiness;

            float Jxx = 1 + J.Dxx * lambda;
            float Jzz = 1 + J.Dzz * lambda;
            float Jzx = J.Dzx * lambda;
            float Jxz = J.Dxz * lambda;

            float left = 0.5 * (Jxx + Jzz);
            float right = 0.5 * pow(pow(Jxx - Jzz, 2) + 4 * Jxz * Jxz, 0.5);
            float J0 = left - right;
            float J1 = left + right;

            float q0 = (J0 - Jxx) / Jxz;
            float q1 = (J1 - Jxx) / Jxz;

            vec2 e0 = vec2(1, q0) * inversesqrt(1 - q0 * q0);
            vec2 e1 = vec2(1, q1) * inversesqrt(1 - q1 * q1);

            color = vec4(e0, e1);
        }
    } else {
        vec2 gv = vec2(gid + 0.5)/vec2(gl_NumWorkGroups * gl_WorkGroupSize);
        float maxL = u.horizontalLength[0];
        float w = 10/float(imageSize(image)).x;
        vec2 x = vec2(gv.x * pc.scale, 0.5);

//        float H = 0;
//        float Dx = 0;
//        float Dz = 0;
//        for(int i = 0; i < 1; ++i) {
//            vec2 uv = fract(x * maxL / u.horizontalLength[i]);
//            vec3 disp = texture(u_DmapSampler, vec3(uv, i)).xyz;
//
//            H += disp.y;
//            Dx += disp.x * u.choppiness;
//            Dz += disp.z * u.choppiness;
//        }

        vec2 uv = fract(x * maxL / u.horizontalLength[0]);
        float H = fx(vec3(uv, 0));

        // TODO this is not going to work we have to sample from a precompouted Jacobian texture
        float J = gx(vec3(uv, 0));

        H = remap(H, u.heightMinMax[0].x, u.heightMinMax[0].y, 0, 1);
        H = smoothstep(0, w, abs(gv.y - H));

        J = smoothstep(0, w, abs(gv.y - J));

        vec3 plot = vec3(0.6);
        float t = H;

        if(J < t) {
            t = J;
            plot = vec3(0, 0, 0.6);
        }

        color.xyz = mix(plot, vec3(1), t);

    }

    imageStore(image, gid, color);
}