#ifndef ATMOSPHERE_COMMON_DEFS_GLSL
#define ATMOSPHERE_COMMON_DEFS_GLSL

#define transmittanceTexture global_textures[nonuniformEXT(atm.transmittanceTextureIndex)]

#define TRANSMITTANCE_TEXTURE_SIZE ivec2(256, 64)
#define TRANSMITTANCE_TEXTURE_SIZE_F vec2(TRANSMITTANCE_TEXTURE_SIZE)
#define MULTI_SCATTERING_TEXTURE_SIZE imageSize(multiScatteringImage)

#define SKY_VIEW_TEXTURE_SIZE ivec2(192, 128)
#define SKY_VIEW_TEXTURE_SIZE_F vec2(SKY_VIEW_TEXTURE_SIZE)

#define AREAL_PERSPECTIVE_TEXTURE_SIZE ivec3(32)
#define AREAL_PERSPECTIVE_TEXTURE_SIZE_F vec3(AREAL_PERSPECTIVE_TEXTURE_SIZE)


#endif // ATMOSPHERE_COMMON_DEFS_GLSL