#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_debug_printf : require

#include "domain.glsl"

#define RAY_TYPE_PRIMIARY 0
#define RAY_TYPE_VOLUME 1

layout(set = 0, binding = 0) uniform accelerationStructure topLevelAs;
layout(set = 0, binding = 2, rgba32f) uniform image2D image;


const float Tmin = 0.001;
const float Tmax = 10000.0;
const int minBounce = 3;

layout(location = 0) rayPayload HitRecord hRec;
layout(location = 1) rayPayload MediumHitRecord mRec;

vec3 envLight(vec3 wi);

Surface toSurface(SurfaceInteraction isect);
vec3 sampleLight(SurfaceInteraction isect, vec3 wo, inout RngStateType rngState);

vec3 sampleMedium(SurfaceInteraction isect, vec3 origin, vec3 wi, inout RngStateType rngState, out MediumInteraction mi);

vec3 medium_Tr(SurfaceInteraction isect, vec3 rayOrigin, vec3 rayDirection, inout RngStateType rngState);

void main(){
    if(currentSample >= sampleCount) return;

    vec2 id = vec2(gl_LaunchID);
    vec2 screenSize = vec2(gl_LaunchSize);
    init(hRec, id, screenSize, frame);

    vec3 throughput = vec3(1);
    vec3 radiance = vec3(0);
    uint flags = gl_RayFlagsOpaqueEXT;

    for(int b = 0; b < maxBounce; ++b) {
        traceRay(topLevelAs, flags, 0xff, RAY_TYPE_PRIMIARY, RayCount, 0, hRec.x, Tmin, hRec.wi, Tmax, 0);

        if(hRec.t == FLT_MAX) {
            radiance += throughput * envLight(hRec.wi);
            break;
        }

        MediumInteraction mi = defaulMi();
        if(hRec.isect.medium != -1) {
            throughput *= sampleMedium(hRec.isect, hRec.x, hRec.wi, hRec.rngState, mi);
            if (isBlack(throughput)) break;
        }

        if(mi.isValid) {
            if(b >= maxBounce - 1) break;

            // TODO sample Light
            hRec.x = offsetRay(mi.x, mi.wi);
            hRec.wi = mi.wi;
        }else {

            // TODO radiance += throughput * emitted light;

            if (hRec.isect.material == -1) {
                hRec.x = offsetRay(hRec.isect.x, hRec.isect.gN);
                b--;
                continue;
            }

            radiance += throughput * sampleLight(hRec.isect, hRec.wo, hRec.rngState);

            Surface surface = toSurface(hRec.isect);
            vec3 brdfWeight = getBrdfWeight(surface, hRec.rngState, hRec.wo, hRec.wi);
            hRec.x = offsetRay(hRec.isect.x, hRec.isect.gN);
            throughput *= brdfWeight;

            if (isBlack(throughput)) break;

            if (b >= maxBounce - 1) break;
        }

        if(b > minBounce) {
            float rrProbability = min(0.95, luminance(throughput));
            if(rrProbability < rand(hRec.rngState)){
                break;
            }
            throughput /= rrProbability;
        }

        reset(hRec);

    }

    if(currentSample > 0) {
        vec3 dst = imageLoad(image, ivec2(gl_LaunchID.xy)).rgb;
        float t = 1.0/float(currentSample+1);
        radiance = mix(dst, radiance, t);
    }

    imageStore(image, ivec2(gl_LaunchID.xy), vec4(radiance, 1));
}

vec3 envLight(vec3 wi) {
    float t = 0.5 + 0.5 * wi.y;
//    return mix(vec3(1.0), vec3(0.5, 0.7, 1.0), t);
    vec2 uv = .5 + .5 * octEncode(normalize(hRec.wi));
    return texture(environment, uv).rgb;
}

Surface toSurface(SurfaceInteraction isect) {
    Material mat = materials[isect.material];

    Surface s;
    s.albedo = mat.diffuse.x != -1 ? mat.diffuse : checkerboard(isect.x, isect.gN, 1);
    s.transmission = vec3(1);
    s.emission = vec3(0);
    s.x = isect.x;
    s.gN = isect.gN;
    s.sN = isect.sN;
    s.roughness = clamp(mat.roughness, 0, 1);
    s.metalness = clamp(mat.metalness, 0, 1);
    s.opacity = 1.0;
    s.inside = false;
    s.volume = false;
    s.ior = 1.0;
    s.bsdf = mat.bsdf;

    return s;
}

vec3 sampleMedium(SurfaceInteraction isect, vec3 origin, vec3 wi, inout RngStateType rngState, out MediumInteraction mi) {
    Medium medium = mediums[isect.medium];
    vec3 sigma_t = medium.extinction;   // Extinction coefficient
    vec3 sigma_s = medium.scattering;   // Scattering coefficient
    float g = medium.g;

    uint flags = gl_RayFlagsOpaqueEXT;

    // TODO offset direction should be based on triangle face, when we use provided normals
    vec3 x = offsetRay(isect.x, -isect.gN);

    // Trace ray through medium to detect distance to surface
    float maxDistance = FLT_MAX;
    if(isect.isFrontFacing){
        traceRay(topLevelAs, flags, 0xff, RAY_TYPE_VOLUME, RayCount, 1, x, 0, wi, Tmax, 1);
        maxDistance = mRec.t;
    }else {
        maxDistance = distance(isect.x, origin);
    }

    mi.isValid = false;

    if (medium.type == MEDIUM_TYPE_HOMOGENEOUS) {
        // Use average sigma_t to avoid spectral imbalance
        float avgSigmaT = max(0.0001, dot(sigma_t, vec3(1.0 / 3.0)));
        float sampledDistance = -log(1.0 - rand(rngState)) / avgSigmaT;
//        debugPrintfEXT("sampledDistance = %f, maxDistance = %f\n", sampledDistance, maxDistance);

        bool scatterOccurred =  sampledDistance < maxDistance;
        float t = min(sampledDistance, maxDistance);

        // Compute transmittance
        vec3 Tr = exp(-sigma_t * t);

        if (scatterOccurred) {
            // Sample scattering direction from Henyey-Greenstein
            vec2 u = vec2(rand(rngState), rand(rngState));
            HG_sample_P(g, -wi, mi.wi, u);

            // Fill medium interaction
            mi.isValid = true;
            mi.x = x + wi * t;
        }

        // Phase function weight
        float phasePdf = 1.0;
        if (mi.isValid) {
            float cosTheta = dot(-wi, mi.wi);
            phasePdf = HG_pdf(g, cosTheta); // scalar
        }

        // PDF for exponential sampling
        float pdf = scatterOccurred ? (avgSigmaT * exp(-avgSigmaT * t)) : exp(-avgSigmaT * maxDistance);

        // Final contribution
        vec3 result;
        if (scatterOccurred) {
            result = Tr * sigma_s * phaseHG(g, dot(-wi, mi.wi)) / max(pdf * phasePdf, 1e-4);
        } else {
            result = Tr / max(pdf, 1e-4);
        }

        return result;
    }
    else if (medium.type == MEDIUM_TYPE_HETAROGENEOUS) {
        Volume volume = volumes[medium.volume];
        float maxDensity = volume.maxDensity;
        vec3 offset = 0.5 / vec3(textureSize(global_textures3D[volume.data], 0));

        if(maxDistance <= 0) return vec3(1);

        // Direction in local volume space
        vec3 dir;
        float tMax;
//        if(isect.isFrontFacing) {
            dir = normalize(mRec.isect.xLocal - isect.xLocal);
            origin = isect.xLocal + dir * offset;
            tMax = distance(isect.xLocal, mRec.isect.xLocal);
//        } else {
//            origin = (inverse(volume.textureToWorldSpace) * vec4(origin, 1)).xyz;
//            dir = normalize(isect.xLocal - origin);
//            tMax = distance(origin, isect.xLocal) - 1e-3;
//            vec3 o = origin;
////            debugPrintfEXT("we inside, origin is [%f, %f, %f], hit is [[%f, %f, %f], tMax: %f\n", o.x, o.y, o.z, x.x, x.y, x.z, tMax);
//        }

        float t = 0.0;
        float sigma_t_scalar = luminance(sigma_t);

        while (true) {
            // Sample distance from exponential with majorant
            t += -log(1.0 - rand(rngState)) / (maxDensity * sigma_t_scalar);
            if (t >= tMax) break;

            vec3 loc = origin + t * dir;

            // Sample the scalar density at this point
            float density = texture(global_textures3D[volume.data], loc).x;

            // Woodcock rejection step
            if (density / maxDensity > rand(rngState)) {
                mi.isValid = true;
                mi.x = mat4x3(volume.textureToWorldSpace) * vec4(loc, 1.0);

                vec2 u = vec2(rand(rngState), rand(rngState));
                HG_sample_P(g, -wi, mi.wi, u);

                // Return properly normalized weight
                return sigma_s / sigma_t;
            }
        }

        return vec3(1.0);
    }

    // Future support for grid-based media
    return vec3(1.0);
}


vec3 sampleLight(SurfaceInteraction isect, vec3 wo, inout RngStateType rngState) {
    vec2 u = vec2(rand(rngState), rand(rngState));

    float pdf, sinTheta;
    vec2 uv = sampleHierarchicalMipMappedTexture(distribution, u, pdf);
    vec3 wi = direction_from_spherical(uv, sinTheta);
    vec3 light_n = -wi;
    vec3 light_x = isect.x + wi * 2 * worldRadius;
    vec3 x = offsetRay(isect.x, isect.gN);
    float NdotL = dot(wi, isect.gN);
    pdf /= 2 * PI * PI * sinTheta;
    vec3 radiance = texture(environment, uv).rgb;

    if(NdotL <= 0) return vec3(0);

    traceRay(topLevelAs, gl_RayFlagsOpaqueEXT, 0xff, RAY_TYPE_PRIMIARY, RayCount, 0, x, Tmin, wi, Tmax, 0);

    if(hRec.t == FLT_MAX) {
        Surface surface = toSurface(isect);
        vec3 brdf = isect.medium == -1 ? vec3(1) : evalBrdf(surface, wo, wi);
        return radiance * brdf / pdf;

    } else {
        if(hRec.isect.medium == -1) return vec3(0);

        x = offsetRay(hRec.isect.x, -hRec.isect.gN);
        wi = hRec.wi;

        float dist = 0;

        traceRay(topLevelAs, gl_RayFlagsOpaqueEXT, 0xff, RAY_TYPE_VOLUME, RayCount, 1, x, 0, wi, Tmax, 1);
        dist = mRec.t;


        vec3 sigma_t = mediums[hRec.isect.medium].extinction;

        // TODO compute transmission for MEDIUM_TYPE_HETAROGENEOUS medium
        return exp(-sigma_t * mRec.t) * radiance;
    }

}