#version 460

#extension GL_GOOGLE_include_directive : enable

#include "whitecaps_common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

vec2 getSpectrum(float k, vec2 s0, vec2 s0c) {
    float w = omega(k);
    float c = cos(w * pc.t);
    float s = sin(w * pc.t);
    return vec2((s0.x + s0c.x) * c - (s0.y + s0c.y) * s, (s0.x - s0c.x) * s + (s0.y - s0c.y) * c);
}

vec2 i(vec2 z) {
    return vec2(-z.y, z.x);
}

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= FFT_SIZE || gid.y >= FFT_SIZE) {
        return;
    }

    vec2 uv = (vec2(gid) + 0.5) / float(FFT_SIZE);
    vec2 st = floor(uv * float(FFT_SIZE)) / float(FFT_SIZE);
    float x = uv.x > 0.5 ? st.x - 1.0 : st.x;
    float y = uv.y > 0.5 ? st.y - 1.0 : st.y;

    vec4 s12 = textureLod(spectrum_1_2_Sampler, uv, 0.0) * 1.414213562;
    vec4 s34 = textureLod(spectrum_3_4_Sampler, uv, 0.0) * 1.414213562;
    vec4 s12c = textureLod(spectrum_1_2_Sampler, vec2(1.0 + 0.5 / float(FFT_SIZE)) - st, 0.0) * 1.414213562;
    vec4 s34c = textureLod(spectrum_3_4_Sampler, vec2(1.0 + 0.5 / float(FFT_SIZE)) - st, 0.0) * 1.414213562;

    vec4 inverseGrid = TWO_PI / pc.GRID_SIZES;
    vec2 k1 = vec2(x, y) * inverseGrid.x;
    vec2 k2 = vec2(x, y) * inverseGrid.y;
    vec2 k3 = vec2(x, y) * inverseGrid.z;
    vec2 k4 = vec2(x, y) * inverseGrid.w;

    float K1 = length(k1);
    float K2 = length(k2);
    float K3 = length(k3);
    float K4 = length(k4);

    float IK1 = K1 == 0.0 ? 0.0 : 1.0 / K1;
    float IK2 = K2 == 0.0 ? 0.0 : 1.0 / K2;
    float IK3 = K3 == 0.0 ? 0.0 : 1.0 / K3;
    float IK4 = K4 == 0.0 ? 0.0 : 1.0 / K4;

    vec2 h1 = getSpectrum(K1, s12.xy, s12c.xy);
    vec2 h2 = getSpectrum(K2, s12.zw, s12c.zw);
    vec2 h3 = getSpectrum(K3, s34.xy, s34c.xy);
    vec2 h4 = getSpectrum(K4, s34.zw, s34c.zw);

    imageStore(fftWavesImage, ivec3(gid, 0), vec4(h1 + i(h2), h3 + i(h4)));
    imageStore(fftWavesImage, ivec3(gid, 1), vec4(i(k1.x * h1) - (k1.y * h1), i(k2.x * h2) - (k2.y * h2)));
    imageStore(fftWavesImage, ivec3(gid, 2), vec4(i(k3.x * h3) - (k3.y * h3), i(k4.x * h4) - (k4.y * h4)));
    imageStore(fftWavesImage, ivec3(gid, 3), imageLoad(fftWavesImage, ivec3(gid, 1)) * vec4(IK1, IK1, IK2, IK2));
    imageStore(fftWavesImage, ivec3(gid, 4), imageLoad(fftWavesImage, ivec3(gid, 2)) * vec4(IK3, IK3, IK4, IK4));

    vec4 IK = vec4(IK1, IK2, IK3, IK4);
    vec2 k1Squared = k1 * k1;
    vec2 k2Squared = k2 * k2;
    vec2 k3Squared = k3 * k3;
    vec2 k4Squared = k4 * k4;
    vec4 tmp = vec4(h1.x, h2.x, h3.x, h4.x);
    imageStore(fftWavesImage, ivec3(gid, 5), -tmp * (vec4(k1Squared.x, k2Squared.x, k3Squared.x, k4Squared.x) * IK));
    imageStore(fftWavesImage, ivec3(gid, 6), -tmp * (vec4(k1Squared.y, k2Squared.y, k3Squared.y, k4Squared.y) * IK));
    imageStore(fftWavesImage, ivec3(gid, 7), -tmp * (vec4(k1.x * k1.y, k2.x * k2.y, k3.x * k3.y, k4.x * k4.y) * IK));
}
