#version 460

#extension GL_EXT_nonuniform_qualifier : enable

#include "octahedral.glsl"
#include "constants.glsl"

#define CAMERA_SET 1
#include "../../camera_uniform.glsl"

layout(set = 2, binding = 10) uniform sampler2D global_textures[];
layout(set = 2, binding = 10) uniform sampler3D global_textures_3d[];

layout(set = 2, binding = 11) uniform writeonly image2D global_images[];
layout(set = 2, binding = 11) uniform writeonly image3D global_images_3d[];

#define GROUP_SIZE 8
#define LOCAL_DATA_SIZE (GROUP_SIZE + 2 * 2)

vec2 resolution = camera.viewportSize;

layout (local_size_x = GROUP_SIZE, local_size_y = GROUP_SIZE, local_size_z = 1) in;

float gaussian_kernel[5][5] = {
{ 0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902 },
{ 0.01330621, 0.0596343, 0.09832033, 0.0596343, 0.01330621 },
{ 0.02193823, 0.09832033, 0.16210282, 0.09832033, 0.02193823 },
{ 0.01330621, 0.0596343, 0.09832033, 0.0596343, 0.01330621 },
{ 0.00296902, 0.01330621, 0.02193823, 0.01330621, 0.00296902 }
};

shared float local_image_data[LOCAL_DATA_SIZE][LOCAL_DATA_SIZE];
shared vec3 local_normal_data[LOCAL_DATA_SIZE][LOCAL_DATA_SIZE];


float visibility_temporal_filter(ivec3 index) {
    if (any(lessThan(index.xy, ivec2(0))) || any(greaterThanEqual(index.xy, ivec2(resolution * 0.5)))) {
        return 0.0;
    }

    vec4 last_visibility_values = texelFetch(global_textures_3d[visibility_cache_texture_index], index, 0);

    float filtered_visibility = 0.25 * (last_visibility_values.x + last_visibility_values.y + last_visibility_values.z + last_visibility_values.w);

    return filtered_visibility;
}

vec3 get_normal(ivec3 index) {

    ivec2 scaled_xy = ivec2(index.xy * resolution_scale_rcp);
    if (any(lessThan(scaled_xy.xy, ivec2(0))) || any(greaterThanEqual(scaled_xy.xy, ivec2(resolution)))) {
        return vec3(0);
    }

    const float raw_depth = texelFetch(global_textures[depth_texture_index], scaled_xy.xy, 0).r;
    if (raw_depth == 1.0f) {
        return vec3(0);
    } else {
        vec2 encoded_normal = texelFetch(global_textures[normals_texture_index], scaled_xy.xy, 0).rg;
        vec3 normal = octDecode(encoded_normal);

        return normal;
    }
}

void main() {
    ivec2 iresolution = ivec2(resolution * 0.5);
    if (gl_GlobalInvocationID.x >= iresolution.x || gl_GlobalInvocationID.y >= iresolution.y)
    return;

    ivec3 local_index = ivec3(gl_LocalInvocationID.xyz) + ivec3(2, 2, 0);
    ivec3 global_index = ivec3(gl_GlobalInvocationID.xyz);

    local_image_data[local_index.y][local_index.x] = visibility_temporal_filter(global_index);
    local_normal_data[local_index.y][local_index.x] = get_normal(global_index);

    if (gl_LocalInvocationID.x == 0 && gl_LocalInvocationID.y == 0) {
        for (int y = -2; y <= -1; ++y) {
            for (int x = -2; x <= -1; ++x) {
                ivec3 offset = ivec3(x, y, 0);
                ivec3 index = local_index + offset;
                ivec3 filter_index = global_index + offset;
                local_image_data[index.y][index.x] = visibility_temporal_filter(filter_index);
                local_normal_data[index.y][index.x] = get_normal(filter_index);
            }
        }
    }

    if (gl_LocalInvocationID.x == 0) {
        for (int i = -2; i <= -1; ++i) {
            ivec3 offset = ivec3(i, 0, 0);
            ivec3 index = local_index + offset;
            ivec3 filter_index = global_index + offset;
            local_image_data[index.y][index.x] = visibility_temporal_filter(filter_index);
            local_normal_data[index.y][index.x] = get_normal(filter_index);
        }
    }

    if (gl_LocalInvocationID.y == 0) {
        for (int i = -2; i <= -1; ++i) {
            ivec3 offset = ivec3(0, i, 0);
            ivec3 index = local_index + offset;
            ivec3 filter_index = global_index + offset;
            local_image_data[index.y][index.x] = visibility_temporal_filter(filter_index);
            local_normal_data[index.y][index.x] = get_normal(filter_index);
        }
    }

    if (gl_LocalInvocationID.x == (GROUP_SIZE - 1) && gl_LocalInvocationID.y == (GROUP_SIZE - 1)) {
        for (int y = 1; y <= 2; ++y) {
            for (int x = 1; x <= 2; ++x) {
                ivec3 offset = ivec3(x, y, 0);
                ivec3 index = local_index + offset;
                ivec3 filter_index = global_index + offset;
                local_image_data[index.y][index.x] = visibility_temporal_filter(filter_index);
                local_normal_data[index.y][index.x] = get_normal(filter_index);
            }
        }
    }

    if (gl_LocalInvocationID.x == (GROUP_SIZE - 1)) {
        for (int i = 1; i <= 2; ++i) {
            ivec3 offset = ivec3(i, 0, 0);
            ivec3 index = local_index + offset;
            ivec3 filter_index = global_index + offset;
            local_image_data[index.y][index.x] = visibility_temporal_filter(filter_index);
            local_normal_data[index.y][index.x] = get_normal(filter_index);
        }
    }

    if (gl_LocalInvocationID.y == (GROUP_SIZE - 1)) {
        for (int i = 1; i <= 2; ++i) {
            ivec3 offset = ivec3(0, i, 0);
            ivec3 index = local_index + offset;
            ivec3 filter_index = global_index + offset;
            local_image_data[index.y][index.x] = visibility_temporal_filter(filter_index);
            local_normal_data[index.y][index.x] = get_normal(filter_index);
        }
    }

    memoryBarrierShared();
    barrier();

    float spatial_filtered_value = 0.0;
    vec3 p_normal = local_normal_data[local_index.y][local_index.x];
    for (int y = -2; y <= 2; ++y) {
        for (int x = -2; x <= 2; ++x) {
            ivec2 index = local_index.xy + ivec2(x, y);

            vec3 q_normal = local_normal_data[local_index.y + y][local_index.x + x];

            if (dot(p_normal, q_normal) <= 0.9) {
                continue;
            }

            float v = local_image_data[index.y][index.x];
            float k = gaussian_kernel[y + 2][x + 2];

            spatial_filtered_value += v * k;
        }
    }

    imageStore(global_images_3d[filtered_visibility_image_index], global_index, vec4(spatial_filtered_value, 0, 0, 0));

//    imageStore(global_images[debug_image_index], global_index.xy, vec4(spatial_filtered_value, 0, 0, 0));

}
