#version 460

/*
Source: Balazs Jako and Balazs Toth, "Fast Hydraulic and Thermal Erosion on the GPU" (CESCG 2011).
URL: https://old.cescg.org/CESCG-2011/papers/TUBudapest-Jako-Balazs.pdf
Equations implemented:
- (15) advect suspended sediment through the velocity field.
*/

layout(local_size_x = 32, local_size_y = 32) in;

#include "constants.glsl"

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID);

    if(!inTerrain(gid)) {
        return;
    }

    const float dt = timeStep;
    vec2 velocity = getVelocityField(gid);
    float st_dt = getSedimentAmountBiLinear(vec2(gid) - velocity * dt);

    setAdvectedSediment(gid, st_dt);
}
