#version 460

/*
Source: Balazs Jako and Balazs Toth, "Fast Hydraulic and Thermal Erosion on the GPU" (CESCG 2011).
URL: https://old.cescg.org/CESCG-2011/papers/TUBudapest-Jako-Balazs.pdf
Equations implemented:
- (15) commit the advected sediment result from the previous pass.
- (16) evaporate water.
*/

layout(local_size_x = 32, local_size_y = 32) in;

#include "constants.glsl"

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID);

    if(!inTerrain(gid)) {
        return;
    }

    const float dt = timeStep;
    const float Ke = evaporationRate;

    float d3 = getWaterHeight(gid);
    float st_dt = getAdvectedSediment(gid);
    float d_t_dt = max(0.0, d3 * (1.0 - Ke * dt));

    int id = gid.y * terrainSize.x + gid.x;
    if(id == 4) {
        debugPrintfEXT("evaporate_water\n");
        debugPrintfEXT("\tst_dt: %.10f, d3: %f, d_t_dt: %f\n", st_dt, d3, d_t_dt);
    }

    setSedimentAmount(gid, st_dt);
    setWaterHeight(gid, d_t_dt);
}
