#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "common.glsl"

#define MESH_SET 0
#include "../shared_lib/mesh_constants.glsl"

#define GLOBAL_CB_SET 1
#include "../shared_lib/constant_buffers.glsl"

layout(local_size_x = WORKGROUP_SIZE) in;

layout(push_constant) uniform Constants {
    uint currentNeighborsBufferIndex;
};

uvec3 Neighbors(uint index) {
    return _NeighborsBuffer[currentNeighborsBufferIndex].v[index];
}

void BisectorElementIndexation(uint currentID);

void main() {
    uint currentID = gl_GlobalInvocationID.x;

    // This thread doesn't have any work to do, we're done
    if (currentID >= _TotalNumElements)
        return;

    BisectorElementIndexation(currentID);
}

void BisectorElementIndexation(uint currentID)
{
    // Grab the current heap ID
    uint64_t cHeapID = _HeapIDBuffer[currentID];

    // Deallocated element, we don't care
    if (cHeapID == 0ul) {
        return;
    }

    // Reserve a slot for this bisector
    uint bisectorSlot = atomicAdd(_IndirectDrawBuffer[0], 3u);

    // Keep track of it's global ID
    _BisectorIndicesBuffer[bisectorSlot / 3u] = currentID;

    // Load the bisector data of the target element
    BisectorData cBisectorData = _BisectorDataBuffer[currentID];

    // Is it visible?
    if ((cBisectorData.flags & VISIBLE_BISECTOR) == 0u) {
        return;
    }

    // Reserve a slot for this visible bisector
    bisectorSlot = atomicAdd(_IndirectDrawBuffer[4], 3u);

    // Keep track of it's global ID
    _VisibleBisectorIndicesBuffer[bisectorSlot / 3u] = currentID;

    // Is it modified?
    if ((cBisectorData.flags & MODIFIED_BISECTOR) == 0u) {
        return;
    }

    // Reserve a slot for this modified bisector
    bisectorSlot = atomicAdd(_IndirectDrawBuffer[8], 4u);

    // Keep track of it's global ID
    _ModifiedBisectorIndicesBuffer[bisectorSlot / 4u] = currentID;
}
