#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_debug_printf : enable

#include "../shared_lib/constant_buffers.glsl"

#define MESH_UPDATE_SET 1
#define MESH_SET 2
#include "common.glsl"

#define MESH_SET 2
#include "../shared_lib/mesh_constants.glsl"

void ClassifyElement(uint currentID, BisectorGeometry bis, uint totalNumElements, uint baseDepth);

layout(local_size_x = WORKGROUP_SIZE) in;
uint currentID;
void main() {
    currentID = gl_GlobalInvocationID.x;
    if (currentID >= _IndirectDrawBuffer[9]) return;

    currentID = _BisectorIndicesBuffer[currentID];

    BisectorGeometry bis;
    bis.p[0] = _CurrentVertexBuffer[3 * currentID];
    bis.p[1] = _CurrentVertexBuffer[3 * currentID + 1];
    bis.p[2] = _CurrentVertexBuffer[3 * currentID + 2];
    bis.p[3] = _CurrentVertexBuffer[3 * _TotalNumElements + currentID];

    ClassifyElement(currentID, bis, _TotalNumElements, _BaseDepth);
}


REAL3_DP NegativeVertex(REAL3_DP bmin, REAL3_DP bmax, REAL3_DP n)
{
    bvec3 b = greaterThan(n, REAL3_DP(0));
    return mix(bmin, bmax, b);
}

//bool FrustumAABBIntersect(in vec4 planes[6], vec3 bmin, vec3 bmax)
//{
//    float a = 1.0;
//
//    for (int i = 0; i < 6 && a >= 0.0; ++i) {
//        vec3 n = NegativeVertex(bmin, bmax, planes[i].xyz);
//        a = dot(vec4(n, 1.0), vec4(planes[i].xyz, planes[i].w));
//    }
//
//    return a >= 0.0;
//}

bool FrustumAABBIntersect(in REAL4_DP frustumPlanes[6], REAL3_DP aabbMin, REAL3_DP aabbMax)
{
    REAL3_DP center = (aabbMax + aabbMin) * REAL_DP(0.5);
    REAL3_DP extents = (aabbMax - aabbMin) * REAL_DP(0.5);
    for (int i = 0; i < 4; i++)
    {
        REAL4_DP plane = frustumPlanes[i];
        REAL3_DP normal_sign = sign(plane.xyz);
        REAL3_DP test_point = center + extents * normal_sign;

        REAL_DP dotProd = dot(test_point, plane.xyz);
        if (dotProd + plane.w < REAL_DP(0))
        return false;
    }
    return true;
}

REAL_DP fifth_root(REAL_DP value) {
    if (value <= REAL_DP(0.0)) return REAL_DP(0.0);

    REAL_DP result = REAL_DP(1.0);
    for (int i = 0; i < 8; ++i) {
        REAL_DP result2 = result * result;
        REAL_DP result4 = result2 * result2;
        result = (REAL_DP(4.0) * result + value / result4) / REAL_DP(5.0);
    }
    return result;
}


void logValididty(BisectorGeometry t, int valididty)  {
//    if(currentID != 0 || currentID != 1 || currentID != 2 || currentID != 3) return;
    switch (valididty) {
        case BACK_FACE_CULLED:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> BACK_FACE_CULLED\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
            break;
        case FRUSTUM_CULLED:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> FRUSTUM_CULLED\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
        break;
        case TOO_SMALL:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> TOO_SMALL\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
            break;
        case UNCHANGED_ELEMENT:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> UNCHANGED_ELEMENT\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
            break;
        case BISECT_ELEMENT:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> BISECT_ELEMENT\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
            break;
        case SIMPLIFY_ELEMENT:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> SIMPLIFY_ELEMENT\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
            break;
        case MERGED_ELEMENT:
            debugPrintfEXT("frame: %u, id: %u, tri: [[%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f], [%.2f, %.2f,%.2f]] -> MERGED_ELEMENT\n",
            _FrameIndex, currentID,
            t.p[0].x, t.p[0].y, t.p[0].z,
            t.p[1].x, t.p[1].y, t.p[1].z,
            t.p[2].x, t.p[2].y, t.p[2].z
            );
            break;
    }
}

int ClassifyBisector(in BisectorGeometry tri, uint depth)
{
    REAL3_DP p0 = REAL3_DP(tri.p[0]);
    REAL3_DP p1 = REAL3_DP(tri.p[1]);
    REAL3_DP p2 = REAL3_DP(tri.p[2]);
    REAL3_DP p3 = REAL3_DP(tri.p[3]);
    REAL3_DP triNormal = normalize(cross(p2 - p1, p0 - p1));
    REAL3_DP triCenter = (p0 + p1 + p2) / REAL_DP(3.0);
    REAL3_DP viewDir = normalize(-triCenter);
    REAL_DP FdotV = dot(viewDir, _UpdateCameraForward);
    REAL_DP VdotN = dot(viewDir, triNormal);

    if (FdotV < REAL_DP(0.0) && VdotN < REAL_DP(-1e-3)) return BACK_FACE_CULLED;

    REAL3_DP aabbMin = min(min(p0, p1), p2);
    REAL3_DP aabbMax = max(max(p0, p1), p2);

    if (!FrustumAABBIntersect(_FrustumPlanes, aabbMin, aabbMax)) return FRUSTUM_CULLED;

    REAL4_DP p0P = _UpdateViewProjectionMatrix * REAL4_DP(p0, REAL_DP(1.0));
    p0P.xy = p0P.xy / p0P.w;
    p0P.xy = (p0P.xy * REAL_DP(0.5) + REAL_DP(0.5));

    REAL4_DP p1P = _UpdateViewProjectionMatrix * REAL4_DP(p1, REAL_DP(1.0));
    p1P.xy = p1P.xy / p1P.w;
    p1P.xy = (p1P.xy * REAL_DP(0.5) + REAL_DP(0.5));

    REAL4_DP p2P = _UpdateViewProjectionMatrix * REAL4_DP(p2, REAL_DP(1.0));
    p2P.xy = p2P.xy / p2P.w;
    p2P.xy = (p2P.xy * REAL_DP(0.5) + REAL_DP(0.5));

    REAL_DP area = REAL_DP(0.5) * abs(p0P.x * (p2P.y - p1P.y) + p1P.x * (p0P.y - p2P.y) + p2P.x * (p1P.y - p0P.y));
    area *= _ScreenSize.x * _ScreenSize.y;

    REAL_DP normalWeight = max(VdotN, REAL_DP(0.0));
    normalWeight = fifth_root(normalWeight);
    REAL_DP areaOverestimation = mix(REAL_DP(2.0), REAL_DP(1.0), normalWeight);
    area *= areaOverestimation;

    if (_TriangleSize < area && depth < _MaxSubdivisionDepth) return BISECT_ELEMENT;

    if ((_TriangleSize * REAL_DP(0.5) > area) || (depth > _MaxSubdivisionDepth)) {
        REAL4_DP p3P = _UpdateViewProjectionMatrix * REAL4_DP(p3, REAL_DP(1.0));
        p3P.xy = p3P.xy / p3P.w;
        p3P.xy = (p3P.xy * REAL_DP(0.5) + REAL_DP(0.5));

        REAL_DP areaParent = REAL_DP(0.5) * abs(p0P.x * (p2P.y - p3P.y) + p3P.x * (p0P.y - p2P.y) + p2P.x * (p3P.y - p0P.y));
        areaParent *= _ScreenSize.x * _ScreenSize.y;
        areaParent *= areaOverestimation;

        return ((_TriangleSize >= areaParent) || (depth > _MaxSubdivisionDepth)) ? TOO_SMALL : UNCHANGED_ELEMENT;
    }

    return UNCHANGED_ELEMENT;
}

void ClassifyElement(uint currentID, BisectorGeometry bis, uint totalNumElements, uint baseDepth)
{
    uint64_t heapID = _HeapIDBuffer[currentID];
    uint depth = HeapIDDepth(heapID);
    BisectorData cbisectorData = _BisectorDataBuffer[currentID];

    cbisectorData.subdivisionPattern = 0;
    cbisectorData.bisectorState = UNCHANGED_ELEMENT;
    cbisectorData.problematicNeighbor = INVALID_POINTER;
    cbisectorData.flags = VISIBLE_BISECTOR;

    int currentValidity = ClassifyBisector(bis, depth);
    logValididty(bis, currentValidity);
    if (currentValidity > UNCHANGED_ELEMENT) {
        cbisectorData.bisectorState = BISECT_ELEMENT;
        uint targetSlot = atomicAdd(_ClassificationBuffer[SPLIT_COUNTER], 1);
        _ClassificationBuffer[CLASSIFY_COUNTER_OFFSET + targetSlot] = currentID;
    } else {
        cbisectorData.flags = currentValidity >= TOO_SMALL ? VISIBLE_BISECTOR : 0;
    }

    if (baseDepth != depth && currentValidity < UNCHANGED_ELEMENT) {
        cbisectorData.bisectorState = SIMPLIFY_ELEMENT;
        if (heapID % 2ul == 0) {
            uint targetSlot = atomicAdd(_ClassificationBuffer[SIMPLIFY_COUNTER], 1);
            _ClassificationBuffer[CLASSIFY_COUNTER_OFFSET + totalNumElements + targetSlot] = currentID;
        }
    }

    _BisectorDataBuffer[currentID] = cbisectorData;
}
