#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_nonuniform_qualifier : require

layout(local_size_x = 1) in;

#define MESH_UPDATE_INDIRECT_BUFFER
#include "common.glsl"

#define MESH_SET 1
#define MESH_SKIP_INDIRECT_DISPATCH_BUFFER
#include "../shared_lib/mesh_constants.glsl"

layout(push_constant) uniform Constants {
    int bufferIndex;
};

void main() {
    uint currentID = gl_GlobalInvocationID.x;
    _IndirectDispatchBuffer[currentID * 3 + 0] = (_WorkListBuffer(bufferIndex)[currentID] + WORKGROUP_SIZE - 1) / WORKGROUP_SIZE;
    _IndirectDispatchBuffer[currentID * 3 + 1] = 1;
    _IndirectDispatchBuffer[currentID * 3 + 2] = 1;
}
