#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define UNSUPPORTED_FIRST_BIT_HIGH

#include "common.glsl"

#define MESH_SET 1
#include "../shared_lib/mesh_constants.glsl"

#define CBT_SET 2
#include "../shared_lib/cbt_constants.glsl"

void ResetBuffers()
{
    _MemoryBuffer[0] = 0;
    _MemoryBuffer[1] = int(cbt_size() - bit_count_buffer());

    _ClassificationBuffer[SPLIT_COUNTER] = 0;
    _ClassificationBuffer[SIMPLIFY_COUNTER] = 0;

    _AllocateBuffer[0] = 0;

    _PropagateBuffer[0] = 0;
    _PropagateBuffer[1] = 0;

    _SimplificationBuffer[0] = 0;

    _IndirectDrawBuffer[0] = 0;
    _IndirectDrawBuffer[1] = 1;
    _IndirectDrawBuffer[2] = 0;
    _IndirectDrawBuffer[3] = 0;

    _IndirectDrawBuffer[4] = 0;
    _IndirectDrawBuffer[5] = 1;
    _IndirectDrawBuffer[6] = 0;
    _IndirectDrawBuffer[7] = 0;

    _IndirectDrawBuffer[8] = 0;
}

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    ResetBuffers();
}
