#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define MESH_UPDATE_SET 0
#include "common.glsl"

#define MESH_SET 1
#include "../shared_lib/mesh_constants.glsl"

layout(local_size_x = WORKGROUP_SIZE) in;

layout(push_constant) uniform Constants {
    uint currentNeighborsBufferIndex;
};

uvec3 Neighbors(uint index) {
    return _NeighborsBuffer[currentNeighborsBufferIndex].v[index];
}

void ValidateBisector(uint currentID);

void main() {
    const uint currentID = gl_GlobalInvocationID.x;

    if (currentID >= _TotalNumElements) {
        return;
    }

    ValidateBisector(currentID);
}

void ValidateBisector(uint currentID) {
    const uint64_t heapID = _HeapIDBuffer[currentID];

    if (heapID == 0ul) {
        return;
    }

    const uvec3 currentNeighbors = Neighbors(currentID);
    bool failed = false;

    for (uint i = 0u; i < 3u; ++i) {
        const uint neighborID = currentNeighbors[i];
        if (neighborID == INVALID_POINTER) {
            continue;
        }

        bool found = false;
        const uvec3 neighborNeighbors = Neighbors(neighborID);
        for (uint j = 0u; j < 3u; ++j) {
            if (neighborNeighbors[j] == currentID) {
                found = true;
            }
        }

        if (!found) {
            failed = true;
            break;
        }
    }

    if (failed) {
        atomicAdd(_ValidationBuffer[0], 1u);
    }
}
