#version 460

#include "common.glsl"

layout(local_size_x = 256) in;

layout(set = 1, binding = 0, scalar) buffer Positions {
    vec3 data[];
} positions[2];

layout(set = 1, binding = 2, scalar) buffer Correction {
    vec3 correction[];
};

uvec3 gridSize = gl_NumWorkGroups * gl_WorkGroupSize;
uint gid = gl_GlobalInvocationID.y * gridSize.x + gl_GlobalInvocationID.x;


void main() {
    if(gid >= global.numObjects) return;

    vec3 x = positions[CURR].data[gid];
    vec3 dx = correction[gid];
    float dt = global.time;

    positions[1].data[gid] = x + dx;

}