#version 460

#include "common.glsl"

layout(local_size_x = 256) in;

layout(set = 1, binding = 0, scalar) buffer Positions {
    vec3 data[];
} positions[2];

layout(set = 1, binding = 1, scalar) buffer Velocity {
    vec3 velocity[];
};

layout(set = 1, binding = 2, scalar) buffer Correction {
    vec3 correction[];
};

layout(set = 1, binding = 3, scalar) buffer Radius {
    float radius[];
};

uvec3 gridSize = gl_NumWorkGroups * gl_WorkGroupSize;
uint gid = gl_GlobalInvocationID.y * gridSize.x + gl_GlobalInvocationID.x;

vec3 walls[5] = vec3[5](
    vec3(0, 1, 0),
    vec3(1, 0, 0),
    vec3(0, 0, 1),
    vec3(-1, 0, 0),
    vec3(0, 0, -1)
);

void main() {
    if(gid >= global.numObjects) return;

    correction[gid] = vec3(0);

    vec3 x = positions[PREV].data[gid];

    if(x.y >= global.domain.upper.y) {
        return;
    }
    float e = 0.9;
    vec3 v = velocity[gid];

    float r = radius[gid];
    vec3 n = vec3(0, 1, 0);
    float d = dot(n, global.domain.lower) + r;
    float l = dot(n, x);

    if(l < d + r) {
        float dd = abs(l - d);
        x += n * dd;
        v = reflect(v,  n);
        positions[PREV].data[gid] = x;
        velocity[gid] = e * v;
        return;
    }

    n = vec3(1, 0, 0);
    d = dot(n, global.domain.lower) + r;
    l = dot(n, x);

    if(l < d + r) {
        float dd = abs(l - d);
        x += n * dd;
        v = reflect(v,  n);
        positions[PREV].data[gid] = x;
        velocity[gid] = e * v;
        return;
    }

    n = vec3(0, 0, 1);
    d = dot(n, global.domain.lower) + r;
    l = dot(n, x);

    if(l < d + r) {
        float dd = abs(l - d);
        x += n * dd;
        v = reflect(v,  n);
        positions[PREV].data[gid] = x;
        velocity[gid] = e * v;
        return;
    }

    n = vec3(-1, 0, 0);
    d = dot(n, global.domain.upper) + r;
    l = dot(n, x);

    if(l < d + r) {
        float dd = abs(l - d);
        x += n * dd;
        v = reflect(v,  n);
        positions[PREV].data[gid] = x;
        velocity[gid] = e * v;
        return;
    }

    n = vec3(0, 0, -1);
    d = dot(n, global.domain.upper) + r;
    l = dot(n, x);

    if(l < d + r) {
        float dd = abs(l - d);
        x += n * dd;
        v = reflect(v,  n);
        positions[PREV].data[gid] = x;
        velocity[gid] = e * v;
        return;
    }

}