#version 460

#include "common.glsl"

layout(local_size_x = 256) in;

layout(set = 1, binding = 0, scalar) buffer Positions {
    vec3 data[];
} positions[2];

layout(set = 1, binding = 1, scalar) buffer Velocity {
    vec3 velocity[];
};

layout(set = 1, binding = 2, scalar) buffer Correction {
    vec3 correction[];
};

layout(set = 1, binding = 3, scalar) buffer Radius {
    float radius[];
};

uvec3 gridSize = gl_NumWorkGroups * gl_WorkGroupSize;
uint gid = gl_GlobalInvocationID.y * gridSize.x + gl_GlobalInvocationID.x;

vec3 walls[5] = vec3[5](
    vec3(0, 1, 0),
    vec3(1, 0, 0),
    vec3(0, 0, 1),
    vec3(-1, 0, 0),
    vec3(0, 0, -1)
);

void main() {
    vec3 x = positions[CURRENT].data[gid];
    float r = global.radius;

    if( any(greaterThan(x, global.domain.upper))) {
        return;
    }

    Domain newDomain = shrink(global.domain, r * 1.1);
    vec3 lower = newDomain.lower;
    vec3 upper = newDomain.upper;
    float rest = 0.5;// Restitution

    positions[CURRENT].data[gid] =  max(lower, min(x, upper));

}