#version 460

#include "common.glsl"

layout(local_size_x = 256) in;

layout(set = 1, binding = 0, scalar) buffer Positions {
    vec3 data[];
} positions[2];

layout(set = 1, binding = 1, scalar) buffer Velocity {
    vec3 velocity[];
};

uvec3 gridSize = gl_NumWorkGroups * gl_WorkGroupSize;
uint gid = gl_GlobalInvocationID.y * gridSize.x + gl_GlobalInvocationID.x;

void main() {
    if(gid >= global.numObjects) return;

    vec3 x = positions[0].data[gid];
    vec3 v = velocity[gid];
    vec3 a = global.gravity;
    float t = global.time;

    v += a * t;
    x += v * t;

    positions[1].data[gid] = x;
    velocity[gid] = v;
}