#version 460

#include "common.glsl"

layout(local_size_x = 256) in;

layout(set = 1, binding = 0, scalar) buffer Positions {
    vec3 data[];
} positions[2];

layout(set = 1, binding = 1, scalar) buffer Velocity {
    vec3 velocity[];
};

uvec3 gridSize = gl_NumWorkGroups * gl_WorkGroupSize;
uint gid = gl_GlobalInvocationID.y * gridSize.x + gl_GlobalInvocationID.x;

void main() {
    if(gid >= global.numObjects) return;

    vec3 a = global.gravity;
    float dt = global.time;

    vec3 p0 = positions[PREVIOUS].data[gid];
    vec3 p1 = positions[CURRENT].data[gid];
    vec3 p2 = 2.f * p1 - p0 + a * dt * dt;

    positions[CURRENT].data[gid] = p2;
    positions[PREVIOUS].data[gid] = p1;
}