#version 460

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_scalar_block_layout : enable

#define CBT_HEAP_BUFFER_BINDING 0
#include "cbt.glsl"

layout(set = 0, binding = 2, scalar) buffer SsboDispatchIndirect {
    uvec3 dispatchCmd;
};

layout(constant_id = 0) const int cbtID = 0;

layout(local_size_x = 1) in;

void main() {
    uint nodeCount = cbt_NodeCount(cbtID);
    dispatchCmd = uvec3(max(nodeCount >> 8, 1), 1, 1);
}