#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "../mesh/common.glsl"

#define MESH_SET 0
#include "../shared_lib/mesh_constants.glsl"

layout(local_size_x = WORKGROUP_SIZE) in;

void main() {
    uint currentID = gl_GlobalInvocationID.x;
    if (currentID >= _TotalNumVertices) return;

    _CurrentVertexBuffer[currentID] = vec3(0.0);
}
