#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_debug_printf : enable


#define GLOBAL_CB_SET 0
#define GLOBAL_CB_BINDING_SLOT 0
#include "../shared_lib/constant_buffers.glsl"

#define MESH_SET 1
#include "../mesh/common.glsl"
#include "../shared_lib/mesh_constants.glsl"

#define LEB_MATRIX_SET 2
#include "../shared_lib/mesh_utilities.glsl"

layout(push_constant) uniform Constants {
    uint complete;
};

layout(local_size_x = WORKGROUP_SIZE) in;

REAL3_DP TransformToPlanetCoordinate(REAL3_DP posPS)
{
    REAL_DP invL = inversesqrt(dot(posPS, posPS));
    return REAL3_DP(_PlanetCenter) + posPS * invL * REAL_DP(_PlanetRadius);
}

void main() {
    uint currentID = gl_GlobalInvocationID.x;
    uint groupIndex = gl_LocalInvocationIndex;

    load_leb_matrix_cache_to_shared_memory(groupIndex);

    uint numBisectors = pre_rendering_frame() ? _IndirectDrawBuffer[9] : (_IndirectDrawBuffer[8] / 4u);

//    debugPrintfEXT("frame: %u, id: %u, numBisectors %u\n", _FrameIndex, currentID, numBisectors);

    if (currentID >= numBisectors)
        return;

    currentID = complete != 0u ? _BisectorIndicesBuffer[currentID] : _ModifiedBisectorIndicesBuffer[currentID];

    uint64_t cHeapID = _HeapIDBuffer[currentID];
    uint depth = HeapIDDepth(cHeapID);

    Triangle parentTri;
    Triangle childTri;
    EvaluateElementPosition(cHeapID, 0u, _BaseDepth, parentTri, childTri);

    Triangle p = parentTri;
    Triangle c = childTri;
//    debugPrintfEXT("frame: %u, id: %u, \n\tparent: [[%f, %f, %f], [%f, %f, %f], [%f, %f, %f]]\n\tchild: [[%f, %f, %f], [%f, %f, %f], [%f, %f, %f]]\n", _FrameIndex, currentID
//    , p.p[0].x, p.p[0].y, p.p[0].z, p.p[1].x, p.p[1].y, p.p[1].z, p.p[2].x, p.p[2].y, p.p[2].z
//    , c.p[0].x, c.p[0].y, c.p[0].z, c.p[1].x, c.p[1].y, c.p[1].z, c.p[2].x, c.p[2].y, c.p[2].z);



    _LEBPositionBuffer[3u * currentID] = TransformToPlanetCoordinate(childTri.p[0]);
    _LEBPositionBuffer[3u * currentID + 1u] = TransformToPlanetCoordinate(childTri.p[1]);
    _LEBPositionBuffer[3u * currentID + 2u] = TransformToPlanetCoordinate(childTri.p[2]);

    if (_BaseDepth < depth) {
        uint parentOffset = 3u * _TotalNumElements;
        _LEBPositionBuffer[parentOffset + currentID] = TransformToPlanetCoordinate((cHeapID & 1ul) == 0ul ? parentTri.p[0] : parentTri.p[2]);
    }
}
