#version 460

#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#define GLOBAL_CB_SET 0
#define GLOBAL_CB_BINDING_SLOT 0
#include "../shared_lib/constant_buffers.glsl"

#define MESH_SET 1
#include "../mesh/common.glsl"
#include "../shared_lib/mesh_constants.glsl"

#define LEB_MATRIX_SET 2
#include "../shared_lib/mesh_utilities.glsl"

layout(push_constant) uniform Constants {
    uint complete;
};

layout(local_size_x = WORKGROUP_SIZE) in;


REAL3_DP TransformToPlanetCoordinate(REAL3_DP posPS) {
    REAL_DP pp = dot(posPS, posPS);
    if(pp == 0.0) return REAL3_DP(0);

    return REAL3_DP(_PlanetCenter) + normalize(posPS) * REAL_DP(_PlanetRadius);
}

void main() {
    uint currentID = gl_GlobalInvocationID.x;
    uint groupIndex = gl_LocalInvocationIndex;

    load_leb_matrix_cache_to_shared_memory(groupIndex);

    uint numBisectors = pre_rendering_frame() ? _IndirectDrawBuffer[9] : (_IndirectDrawBuffer[8] / 4u);

    if (currentID >= numBisectors)
        return;

    currentID = complete != 0u ? _BisectorIndicesBuffer[currentID] : _ModifiedBisectorIndicesBuffer[currentID];

    uint64_t cHeapID = _HeapIDBuffer[currentID];
    uint depth = HeapIDDepth(cHeapID);

    Triangle parentTri;
    Triangle childTri;
    EvaluateElementPosition(cHeapID, 0u, _BaseDepth, parentTri, childTri);

    _LEBPositionBuffer[3u * currentID] = TransformToPlanetCoordinate(childTri.p[0]);
    _LEBPositionBuffer[3u * currentID + 1u] = TransformToPlanetCoordinate(childTri.p[1]);
    _LEBPositionBuffer[3u * currentID + 2u] = TransformToPlanetCoordinate(childTri.p[2]);

    if (_BaseDepth < depth) {
        uint parentOffset = 3u * _TotalNumElements;
        _LEBPositionBuffer[parentOffset + currentID] = TransformToPlanetCoordinate((cHeapID & 1ul) == 0ul ? parentTri.p[0] : parentTri.p[2]);
    }
}