#version 460

#extension GL_EXT_nonuniform_qualifier : require

#include "hash.glsl"

#define displacement_map global_images[dmap_image_index]

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 11, r16f) uniform image2D global_images[];

layout(push_constant) uniform Constants {
    vec2 seed;
    uint maxIterations;
    uint iteration;
    uint dmap_image_index;
};

void main() {
    ivec2 gid = ivec2(gl_GlobalInvocationID);

    if(iteration >= maxIterations) {
        // use arithmetric sequence formula
        const float n = maxIterations;
        const float d = -1.0/n;
        const float a1 = 1;
        const float sum = n * (2 * a1 + (n - 1) * d) * 0.5;

        float cur_height = imageLoad(displacement_map, gid).r;
        float normalized_height = cur_height/sum;
        imageStore(displacement_map, gid, vec4(normalized_height));
        return;
    }

    vec2 x = -1 + 2 * vec2(gid + 0.5)/vec2(gl_NumWorkGroups * gl_WorkGroupSize);

    vec4 rp = hash42(seed + (iteration * 409));
    vec2 n = -1 + 2 * rp.xy;
    vec2 p = -1 + 2 * rp.zw;
    float d = dot(n, p);


    float cur_height = imageLoad(displacement_map, gid).r;
    float height = 1 - float(iteration)/maxIterations;

    float h = cur_height + step(d, dot(n, x)) * height;
    imageStore(displacement_map, gid, vec4(h));

}