#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_scalar_block_layout : require

#include "ray_tracing_lang.glsl"
#include "raytracing_implicits/implicits.glsl"


layout(buffer_reference, buffer_reference_align=8) buffer SphereBuffer {
    Sphere at[];
};

layout(shaderRecord, std430) buffer SBT {
    SphereBuffer spheres;
};

hitAttributeEXT vec2 attribs;

void main() {
    Ray ray = Ray(gl_WorldRayOrigin, gl_WorldRayDirection);
    vec2 t = vec2(0);

    Sphere sphere = spheres.at[gl_PrimitiveID];
    if (sphere_ray_test(sphere, ray, t)){
        attribs = getUV(sphere, ray, t.x);

        reportIntersection(t.x, IMPLICIT_TYPE_SPHERE);
    }
}